package com.example.countingdowngame.wildCards.wildCardTypes;

import com.example.countingdowngame.wildCards.WildCardProperties;

public class WildCardData {
    public static final WildCardProperties[] QUIZ_WILD_CARDS = {
            // Science Quiz Questions
            new WildCardProperties("Quiz! What is the deepest ocean on Earth?", 10, true, true, "Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Science"),
            new WildCardProperties("Quiz! How many sides does a heptagon have?", 10, true, true, "7", "5", "8", "6", "Science"),
            new WildCardProperties("Quiz! What is the largest planet in our solar system?", 10, true, true, "Jupiter", "Mars", "Saturn", "Neptune", "Science"),
            new WildCardProperties("Quiz! Can you name all seven colors of the rainbow in order?", 10, true, true, "Red, Orange, Yellow, Green, Blue, Indigo, Violet", "Red, Blue, Yellow, Green, Purple, Pink, Orange", "Yellow, Green, Blue, Purple, Orange, Indigo, Red", "Black, White, Red, Blue, Green, Yellow, Orange", "Science"),
            new WildCardProperties("Quiz! What is the formula for calculating the area of a circle?", 10, true, true, "πr^2", "2πr", "πr", "πr/2", "Science"),
            new WildCardProperties("Quiz! What is the boiling point of water in Fahrenheit?", 10, true, true, "212", "100", "180", "32", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for silver on the periodic table?", 10, true, true, "Ag", "Au", "Si", "Pt", "Science"),
            new WildCardProperties("Quiz! What is the chemical formula for glucose?", 10, true, true, "C6H12O6", "CO2", "H2O", "CH4", "Science"),
            new WildCardProperties("Quiz! How many chromosomes are in a human body cell?", 10, true, true, "46", "23", "48", "20", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for helium on the periodic table?", 10, true, true, "He", "H", "Ha", "Ho", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for oxygen on the periodic table?", 10, true, true, "O", "Om", "On", "Op", "Science"),
            new WildCardProperties("Quiz! What is the boiling point of water in Celsius?", 10, true, true, "100", "0", "50", "200", "Science"),
            new WildCardProperties("Quiz! Who developed the theory of general relativity?", 10, true, true, "Albert Einstein", "Isaac Newton", "Stephen Hawking", "Nikola Tesla", "Science"),
            new WildCardProperties("Quiz! What is the atomic number of hydrogen?", 10, true, true, "1", "2", "3", "0", "Science"),
            new WildCardProperties("Quiz! What is the largest organ in the human body?", 10, true, true, "Skin", "Heart", "Brain", "Liver", "Science"),
            new WildCardProperties("Quiz! How many chromosomes are in a human body cell?", 10, true, true, "46", "23", "48", "20", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for helium on the periodic table?", 10, true, true, "He", "H", "C", "O", "Science"),
            new WildCardProperties("Quiz! Who discovered penicillin?", 10, true, true, "Alexander Fleming", "Louis Pasteur", "Marie Curie", "Isaac Newton", "Science"),
            new WildCardProperties("Quiz! What is the formula for calculating the area of a circle?", 10, true, true, "πr^2", "2πr", "πd", "πr", "Science"),
            new WildCardProperties("Quiz! What is the largest species of shark?", 10, true, true, "Whale Shark", "Great White Shark", "Hammerhead Shark", "Tiger Shark", "Science"),
            new WildCardProperties("Quiz! What is the boiling point of water in Fahrenheit?", 10, true, true, "212", "100", "32", "0", "Science"),
            new WildCardProperties("Quiz! Who is known as the 'father of modern chemistry'?", 10, true, true, "Antoine Lavoisier", "John Dalton", "Dmitri Mendeleev", "Robert Boyle", "Science"),
            new WildCardProperties("Quiz! What is the formula for calculating density?", 10, true, true, "Density = Mass / Volume", "Density = Mass x Volume", "Density = Mass + Volume", "Density = Volume / Mass", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for iron on the periodic table?", 10, true, true, "Fe", "Ir", "Au", "Pb", "Science"),
            new WildCardProperties("Quiz! Who proposed the theory of evolution by natural selection?", 10, true, true, "Charles Darwin", "Gregor Mendel", "Alfred Russel Wallace", "Jean-Baptiste Lamarck", "Science"),
            new WildCardProperties("Quiz! What is the largest moon in the solar system?", 10, true, true, "Ganymede", "Titan", "Callisto", "Io", "Science"),
            new WildCardProperties("Quiz! What is the freezing point of water in Celsius?", 10, true, true, "0", "-10", "10", "100", "Science"),
            new WildCardProperties("Quiz! Who discovered the law of gravity?", 10, true, true, "Isaac Newton", "Galileo Galilei", "Johannes Kepler", "Albert Einstein", "Science"),
            new WildCardProperties("Quiz! What is the chemical formula for glucose?", 10, true, true, "C6H12O6", "CO2", "C6H6O3", "CH4", "Science"),
            new WildCardProperties("Quiz! Who invented the first practical telephone?", 10, true, true, "Alexander Graham Bell", "Thomas Edison", "Guglielmo Marconi", "Nikola Tesla", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for sodium on the periodic table?", 10, true, true, "Na", "So", "Sa", "Ni", "Science"),
            new WildCardProperties("Quiz! What is the process by which plants release water vapor through their leaves?", 10, true, true, "Transpiration", "Photosynthesis", "Respiration", "Condensation", "Science"),
            new WildCardProperties("Quiz! What is the unit of measurement for energy?", 10, true, true, "Joule (J)", "Watt (W)", "Newton (N)", "Volt (V)", "Science"),
            new WildCardProperties("Quiz! What is the hardest substance in the human body?", 10, true, true, "Tooth enamel", "Bones", "Cartilage", "Nails", "Science"),
            new WildCardProperties("Quiz! What is the chemical formula for sulfuric acid?", 10, true, true, "H2SO4", "HCl", "HNO3", "CH3COOH", "Science"),
            new WildCardProperties("Quiz! What is the process of a gas turning into a liquid?", 10, true, true, "Condensation", "Evaporation", "Sublimation", "Freezing", "Science"),
            new WildCardProperties("Quiz! Which gas makes up about 78% of the Earth's atmosphere?", 10, true, true, "Nitrogen (N2)", "Oxygen (O2)", "Carbon dioxide (CO2)", "Argon (Ar)", "Science"),
            new WildCardProperties("Quiz! What is the unit of measurement for frequency?", 10, true, true, "Hertz (Hz)", "Watt (W)", "Joule (J)", "Newton (N)", "Science"),
            new WildCardProperties("Quiz! What is the process of a solid turning directly into a gas?", 10, true, true, "Sublimation", "Condensation", "Evaporation", "Melting", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for copper on the periodic table?", 10, true, true, "Cu", "Co", "Cp", "Cr", "Science"),
            new WildCardProperties("Quiz! What is the name for the study of fossils?", 10, true, true, "Paleontology", "Geology", "Archeology", "Biology", "Science"),
            new WildCardProperties("Quiz! What is the unit of measurement for electric potential difference?", 10, true, true, "Volt (V)", "Ampere (A)", "Ohm (Ω)", "Watt (W)", "Science"),
            new WildCardProperties("Quiz! Which gas do humans exhale during respiration?", 10, true, true, "Carbon dioxide (CO2)", "Oxygen (O2)", "Nitrogen (N2)", "Methane (CH4)", "Science"),
            new WildCardProperties("Quiz! What is the process of a liquid turning into a solid?", 10, true, true, "Freezing", "Melting", "Condensation", "Evaporation", "Science"),
            new WildCardProperties("Quiz! What is the chemical formula for methane?", 10, true, true, "CH4", "CO2", "H2O", "C6H12O6", "Science"),
            new WildCardProperties("Quiz! What is the process of energy transfer through electromagnetic waves?", 10, true, true, "Radiation", "Conduction", "Convection", "Transfusion", "Science"),
            new WildCardProperties("Quiz! Which gas is produced during photosynthesis?", 10, true, true, "Oxygen (O2)", "Carbon dioxide (CO2)", "Nitrogen (N2)", "Hydrogen (H2)", "Science"),
            new WildCardProperties("Quiz! What is the unit of measurement for electric resistance?", 10, true, true, "Ohm (Ω)", "Volt (V)", "Ampere (A)", "Watt (W)", "Science"),
            new WildCardProperties("Quiz! What is the process of a liquid turning into a gas below its boiling point?", 10, true, true, "Evaporation", "Condensation", "Sublimation", "Melting", "Science"),

// Geography Quiz Questions
            new WildCardProperties("Quiz! What is the national animal of Canada?", 10, true, true, "Beaver", "Moose", "Polar Bear", "Eagle", "Geography"),
            new WildCardProperties("Quiz! How many time zones are there in the world?", 10, true, true, "24", "12", "36", "48", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Brazil?", 10, true, true, "Brasília", "Rio de Janeiro", "São Paulo", "Salvador", "Geography"),
            new WildCardProperties("Quiz! Which country is known as the 'Land of the Rising Sun'?", 10, true, true, "Japan", "China", "Korea", "Vietnam", "Geography"),
            new WildCardProperties("Quiz! In which continent is the Sahara Desert located?", 10, true, true, "Africa", "Asia", "South America", "Europe", "Geography"),
            new WildCardProperties("Quiz! What is the largest country by land area?", 10, true, true, "Russia", "Canada", "China", "United States", "Geography"),
            new WildCardProperties("Quiz! What is the highest mountain in the world?", 10, true, true, "Mount Everest", "K2", "Kangchenjunga", "Lhotse", "Geography"),
            new WildCardProperties("Quiz! What is the largest ocean?", 10, true, true, "Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Australia?", 10, true, true, "Canberra", "Sydney", "Melbourne", "Perth", "Geography"),
            new WildCardProperties("Quiz! Which river is the longest in the world?", 10, true, true, "Nile", "Amazon", "Yangtze", "Mississippi", "Geography"),
            new WildCardProperties("Quiz! What is the official language of Japan?", 10, true, true, "Japanese", "Korean", "Mandarin", "Vietnamese", "Geography"),
            new WildCardProperties("Quiz! Which city is known as the 'Eternal City'?", 10, true, true, "Rome", "Athens", "Jerusalem", "Paris", "Geography"),
            new WildCardProperties("Quiz! What is the largest desert in the world?", 10, true, true, "Antarctica", "Sahara", "Arabian", "Gobi", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Canada?", 10, true, true, "Ottawa", "Toronto", "Montreal", "Vancouver", "Geography"),
            new WildCardProperties("Quiz! Which country is famous for the Great Barrier Reef?", 10, true, true, "Australia", "Philippines", "Indonesia", "Maldives", "Geography"),
            new WildCardProperties("Quiz! What is the official language of Brazil?", 10, true, true, "Portuguese", "Spanish", "French", "Italian", "Geography"),
            new WildCardProperties("Quiz! In which country is the Taj Mahal located?", 10, true, true, "India", "Pakistan", "Bangladesh", "Nepal", "Geography"),
            new WildCardProperties("Quiz! What is the largest lake in Africa?", 10, true, true, "Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad", "Geography"),
            new WildCardProperties("Quiz! What is the currency of Japan?", 10, true, true, "Japanese yen", "Japanese won", "Japanese dollar", "Japanese pound", "Geography"),
            new WildCardProperties("Quiz! In which country is Mount Kilimanjaro located?", 10, true, true, "Tanzania", "Kenya", "Uganda", "Zimbabwe", "Geography"),
            new WildCardProperties("Quiz! What is the smallest country in the world?", 10, true, true, "Vatican City", "Monaco", "Nauru", "Tuvalu", "Geography"),
            new WildCardProperties("Quiz! Which country is known for the Pyramids of Giza?", 10, true, true, "Egypt", "Greece", "Turkey", "Iraq", "Geography"),
            new WildCardProperties("Quiz! Which country is the largest archipelago in the world?", 10, true, true, "Indonesia", "Philippines", "Japan", "Maldives", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Spain?", 10, true, true, "Madrid", "Barcelona", "Seville", "Valencia", "Geography"),
            new WildCardProperties("Quiz! Which river runs through the Grand Canyon in the United States?", 10, true, true, "Colorado River", "Mississippi River", "Missouri River", "Ohio River", "Geography"),
            new WildCardProperties("Quiz! In which continent is the Andes mountain range located?", 10, true, true, "South America", "North America", "Europe", "Asia", "Geography"),
            new WildCardProperties("Quiz! What is the largest island in the Mediterranean Sea?", 10, true, true, "Sicily", "Sardinia", "Cyprus", "Corsica", "Geography"),
            new WildCardProperties("Quiz! Which African country is known as the 'Pearl of the Indian Ocean'?", 10, true, true, "Sri Lanka", "Madagascar", "Mauritius", "Maldives", "Geography"),
            new WildCardProperties("Quiz! What is the official language of Germany?", 10, true, true, "German", "Dutch", "Swedish", "Norwegian", "Geography"),
            new WildCardProperties("Quiz! Which country is the world's leading producer of coffee?", 10, true, true, "Brazil", "Colombia", "Vietnam", "Ethiopia", "Geography"),
            new WildCardProperties("Quiz! What is the smallest continent in the world?", 10, true, true, "Australia", "Asia", "Europe", "North America", "Geography"),
            new WildCardProperties("Quiz! Which river is known as the 'Mother River' in China?", 10, true, true, "Yangtze River", "Yellow River", "Mekong River", "Indus River", "Geography"),
            new WildCardProperties("Quiz! What is the capital of South Africa?", 10, true, true, "Pretoria", "Cape Town", "Johannesburg", "Durban", "Geography"),
            new WildCardProperties("Quiz! Which country is the Land of a Thousand Lakes?", 10, true, true, "Finland", "Sweden", "Norway", "Denmark", "Geography"),
            new WildCardProperties("Quiz! In which U.S. state is the Grand Canyon located?", 10, true, true, "Arizona", "Utah", "Nevada", "Colorado", "Geography"),
            new WildCardProperties("Quiz! Which country is home to the famous rock formation Uluru (Ayers Rock)?", 10, true, true, "Australia", "New Zealand", "Fiji", "Papua New Guinea", "Geography"),
            new WildCardProperties("Quiz! What is the largest city in Canada?", 10, true, true, "Toronto", "Vancouver", "Montreal", "Calgary", "Geography"),
            new WildCardProperties("Quiz! Which river is the longest in Europe?", 10, true, true, "Volga River", "Danube River", "Rhine River", "Dnieper River", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Argentina?", 10, true, true, "Buenos Aires", "Santiago", "Lima", "Brasilia", "Geography"),
            new WildCardProperties("Quiz! Which country is known as the 'Land of Fire and Ice'?", 10, true, true, "Iceland", "Greenland", "Norway", "Finland", "Geography"),
            new WildCardProperties("Quiz! What is the highest waterfall in the world?", 10, true, true, "Angel Falls", "Niagara Falls", "Victoria Falls", "Iguaçu Falls", "Geography"),
            new WildCardProperties("Quiz! Which city is located on two continents, Europe and Asia?", 10, true, true, "Istanbul", "Athens", "Ankara", "Bucharest", "Geography"),
            new WildCardProperties("Quiz! Which country is known as the 'Land of the Midnight Sun'?", 10, true, true, "Norway", "Sweden", "Finland", "Iceland", "Geography"),
            new WildCardProperties("Quiz! What is the largest river in the world by discharge volume?", 10, true, true, "Amazon River", "Nile River", "Congo River", "Mississippi River", "Geography"),
            new WildCardProperties("Quiz! Which country is famous for its tulip fields and windmills?", 10, true, true, "Netherlands", "Belgium", "Denmark", "Luxembourg", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Russia?", 10, true, true, "Moscow", "St. Petersburg", "Novosibirsk", "Yekaterinburg", "Geography"),
            new WildCardProperties("Quiz! Which African country is known as the 'Pearl of Africa'?", 10, true, true, "Uganda", "Kenya", "Tanzania", "Rwanda", "Geography"),
            new WildCardProperties("Quiz! In which mountain range is Mount Everest located?", 10, true, true, "Himalayas", "Andes", "Alps", "Rocky Mountains", "Geography"),
            new WildCardProperties("Quiz! What is the largest hot desert in the world?", 10, true, true, "Sahara Desert", "Arabian Desert", "Gobi Desert", "Kalahari Desert", "Geography"),
            new WildCardProperties("Quiz! Which country is famous for the Great Wall?", 10, true, true, "China", "Japan", "Korea", "Mongolia", "Geography"),

// History Quiz Questions
            new WildCardProperties("Quiz! Who is the current Prime Minister of Japan?", 10, true, true, "Yoshihide Suga", "Shinzo Abe", "Naoto Kan", "Junichiro Koizumi", "History"),
            new WildCardProperties("Quiz! In which year did World War I begin?", 10, true, true, "1914", "1916", "1917", "1918", "History"),
            new WildCardProperties("Quiz! Who was the first President of the United States?", 10, true, true, "George Washington", "Thomas Jefferson", "John Adams", "James Madison", "History"),
            new WildCardProperties("Quiz! In which year did the United States declare independence from Great Britain?", 10, true, true, "1776", "1781", "1799", "1804", "History"),
            new WildCardProperties("Quiz! Who was the leader of the Soviet Union during World War II?", 10, true, true, "Joseph Stalin", "Vladimir Lenin", "Nikita Khrushchev", "Leon Trotsky", "History"),
            new WildCardProperties("Quiz! Who painted the Mona Lisa?", 10, true, true, "Leonardo da Vinci", "Michelangelo", "Raphael", "Vincent van Gogh", "History"),
            new WildCardProperties("Quiz! In which year did the Titanic sink?", 10, true, true, "1912", "1909", "1915", "1917", "History"),
            new WildCardProperties("Quiz! Who wrote the play 'Romeo and Juliet'?", 10, true, true, "William Shakespeare", "Christopher Marlowe", "John Donne", "George Bernard Shaw", "History"),
            new WildCardProperties("Quiz! In which year did the American Civil War end?", 10, true, true, "1865", "1863", "1867", "1870", "History"),
            new WildCardProperties("Quiz! Who was the first female Prime Minister of the United Kingdom?", 10, true, true, "Margaret Thatcher", "Theresa May", "Indira Gandhi", "Angela Merkel", "History"),
            new WildCardProperties("Quiz! In which country was Adolf Hitler born?", 10, true, true, "Austria", "Germany", "Switzerland", "Poland", "History"),
            new WildCardProperties("Quiz! What is the significance of the Magna Carta?", 10, true, true, "It established the principle of the rule of law", "It granted universal suffrage", "It abolished slavery", "It established a parliamentary system", "History"),
            new WildCardProperties("Quiz! Who was the last pharaoh of ancient Egypt?", 10, true, true, "Cleopatra", "Ramses II", "Nefertiti", "Hatshepsut", "History"),
            new WildCardProperties("Quiz! In which year did the Berlin Wall fall?", 10, true, true, "1989", "1991", "1987", "1993", "History"),
            new WildCardProperties("Quiz! Who was the first man to walk on the moon?", 10, true, true, "Neil Armstrong", "Buzz Aldrin", "Alan Shepard", "Yuri Gagarin", "History"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Starry Night'?", 10, true, true, "Vincent van Gogh", "Pablo Picasso", "Claude Monet", "Salvador Dalí", "History"),
            new WildCardProperties("Quiz! In which year did World War II end?", 10, true, true, "1945", "1943", "1947", "1950", "History"),
            new WildCardProperties("Quiz! Who wrote the novel 'Pride and Prejudice'?", 10, true, true, "Jane Austen", "Charlotte Bronte", "Charles Dickens", "Mark Twain", "History"),
            new WildCardProperties("Quiz! What is the significance of the Declaration of Independence?", 10, true, true, "It announced the United States' independence from Great Britain", "It ended slavery in the United States", "It established a federal government", "It granted universal suffrage", "History"),
            new WildCardProperties("Quiz! Who was the first Emperor of Rome?", 10, true, true, "Augustus", "Julius Caesar", "Nero", "Caligula", "History"),
            new WildCardProperties("Quiz! In which year did the Renaissance begin?", 10, true, true, "14th century", "15th century", "16th century", "17th century", "History"),
            new WildCardProperties("Quiz! Who was the founder of the Mongol Empire?", 10, true, true, "Genghis Khan", "Kublai Khan", "Timur", "Attila the Hun", "History"),
            new WildCardProperties("Quiz! In which year did the French Revolution begin?", 10, true, true, "1789", "1776", "1792", "1800", "History"),
            new WildCardProperties("Quiz! Who was the first female pharaoh of ancient Egypt?", 10, true, true, "Hatshepsut", "Cleopatra", "Nefertiti", "Meritaten", "History"),
            new WildCardProperties("Quiz! In which year did the Industrial Revolution start?", 10, true, true, "1760", "1789", "1801", "1848", "History"),
            new WildCardProperties("Quiz! Who was the first woman to fly solo across the Atlantic?", 10, true, true, "Amelia Earhart", "Bessie Coleman", "Jacqueline Cochran", "Harriet Quimby", "History"),
            new WildCardProperties("Quiz! In which year did the Cuban Missile Crisis occur?", 10, true, true, "1962", "1960", "1963", "1959", "History"),
            new WildCardProperties("Quiz! Who was the first African American President of the United States?", 10, true, true, "Barack Obama", "Martin Luther King Jr.", "Malcolm X", "Jesse Jackson", "History"),
            new WildCardProperties("Quiz! In which year did the Battle of Gettysburg take place during the American Civil War?", 10, true, true, "1863", "1861", "1865", "1867", "History"),
            new WildCardProperties("Quiz! Who was the first woman to win a Nobel Prize?", 10, true, true, "Marie Curie", "Rosalind Franklin", "Dorothy Crowfoot Hodgkin", "Ada Yonath", "History"),
            new WildCardProperties("Quiz! In which year did the Russian Revolution occur?", 10, true, true, "1917", "1905", "1915", "1920", "History"),
            new WildCardProperties("Quiz! Who was the first European explorer to reach India by sea?", 10, true, true, "Vasco da Gama", "Christopher Columbus", "Ferdinand Magellan", "Amerigo Vespucci", "History"),
            new WildCardProperties("Quiz! In which year did the American Revolution end?", 10, true, true, "1783", "1776", "1791", "1800", "History"),
            new WildCardProperties("Quiz! Who was the Roman general who led the conquest of Gaul?", 10, true, true, "Julius Caesar", "Augustus", "Mark Antony", "Pompey the Great", "History"),
            new WildCardProperties("Quiz! In which year did the Treaty of Versailles end World War I?", 10, true, true, "1919", "1920", "1918", "1921", "History"),
            new WildCardProperties("Quiz! Who was the legendary king of Uruk in ancient Mesopotamia?", 10, true, true, "Gilgamesh", "Enkidu", "Ninsun", "Lugalbanda", "History"),
            new WildCardProperties("Quiz! In which century did the American colonies declare independence from Spain?", 10, true, true, "1800's", "1700's", "1600's", "1900's", "History"),
            new WildCardProperties("Quiz! Who was the first Roman Emperor?", 10, true, true, "Augustus", "Tiberius", "Julius Caesar", "Nero", "History"),
            new WildCardProperties("Quiz! In which year did the Treaty of Paris end the American Revolutionary War?", 10, true, true, "1783", "1776", "1791", "1800", "History"),
            new WildCardProperties("Quiz! Who was the leader of the Bolshevik Party during the October Revolution?", 10, true, true, "Vladimir Lenin", "Leon Trotsky", "Joseph Stalin", "Nikolai Bukharin", "History"),
            new WildCardProperties("Quiz! In which year did the Black Death (Bubonic Plague) spread across Europe?", 10, true, true, "1347", "1400", "1300", "1368", "History"),
            new WildCardProperties("Quiz! Who was the first female astronaut to travel to space?", 10, true, true, "Valentina Tereshkova", "Sally Ride", "Judith Resnik", "Mae Jemison", "History"),
            new WildCardProperties("Quiz! In which year did the Spanish conquistador Hernán Cortés conquer the Aztec Empire?", 10, true, true, "1521", "1492", "1533", "1565", "History"),
            new WildCardProperties("Quiz! Who was the ancient Egyptian queen who ruled alongside her husband, Pharaoh Akhenaten?", 10, true, true, "Nefertiti", "Cleopatra", "Hatshepsut", "Meritaten", "History"),
            new WildCardProperties("Quiz! In which year did the Battle of Waterloo take place, leading to the defeat of Napoleon Bonaparte?", 10, true, true, "1815", "1812", "1818", "1820", "History"),
            new WildCardProperties("Quiz! Who was the first President of the United States to be impeached?", 10, true, true, "Andrew Johnson", "Bill Clinton", "Richard Nixon", "Donald Trump", "History"),
            new WildCardProperties("Quiz! In which year did the Great Fire of London devastate the city?", 10, true, true, "1666", "1665", "1667", "1670", "History"),
            new WildCardProperties("Quiz! Who was the Mongol emperor who established the Yuan Dynasty in China?", 10, true, true, "Kublai Khan", "Genghis Khan", "Ogedei Khan", "Möngke Khan", "History"),
            new WildCardProperties("Quiz! In which year did the Suez Canal open, connecting the Mediterranean Sea to the Red Sea?", 10, true, true, "1869", "1870", "1867", "1872", "History"),
            new WildCardProperties("Quiz! Who was the leader of the Allied forces during World War II?", 10, true, true, "Dwight D. Eisenhower", "George S. Patton", "Douglas MacArthur", "Bernard Montgomery", "History"),
// Art/Music Quiz Questions
            new WildCardProperties("Quiz! How many symphonies did Ludwig van Beethoven compose?", 10, true, true, "9", "5", "7", "10", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Mona Lisa'?", 10, true, true, "Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Edvard Munch", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous symphony 'Symphony No. 9'?", 10, true, true, "Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Johannes Brahms", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Persistence of Memory'?", 10, true, true, "Salvador Dalí", "Pablo Picasso", "Vincent van Gogh", "Edvard Munch", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous opera 'The Barber of Seville'?", 10, true, true, "Gioachino Rossini", "Wolfgang Amadeus Mozart", "Giuseppe Verdi", "Richard Wagner", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead singer of the band Nirvana?", 10, true, true, "Kurt Cobain", "Dave Grohl", "Eddie Vedder", "Chris Cornell", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'Water Lilies'?", 10, true, true, "Claude Monet", "Edgar Degas", "Henri Matisse", "Georges Seurat", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous symphonic poem 'Also sprach Zarathustra'?", 10, true, true, "Richard Strauss", "Antonín Dvořák", "Gustav Mahler", "Johannes Brahms", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the play 'Macbeth'?", 10, true, true, "William Shakespeare", "Christopher Marlowe", "George Bernard Shaw", "Oscar Wilde", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Thinker'?", 10, true, true, "Auguste Rodin", "Pablo Picasso", "Vincent van Gogh", "Edvard Munch", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous ballet 'Sleeping Beauty'?", 10, true, true, "Pyotr Ilyich Tchaikovsky", "Claude Debussy", "Sergei Prokofiev", "Igor Stravinsky", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the novel '1984'?", 10, true, true, "George Orwell", "Aldous Huxley", "Ray Bradbury", "Jules Verne", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Kiss'?", 10, true, true, "Gustav Klimt", "Édouard Manet", "Henri de Toulouse-Lautrec", "Camille Pissarro", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous opera 'La bohème'?", 10, true, true, "Giacomo Puccini", "Giuseppe Verdi", "Richard Wagner", "Wolfgang Amadeus Mozart", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the play 'The Importance of Being Earnest'?", 10, true, true, "Oscar Wilde", "George Bernard Shaw", "Anton Chekhov", "Samuel Beckett", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'American Gothic'?", 10, true, true, "Grant Wood", "Edward Hopper", "Georgia O'Keeffe", "Jackson Pollock", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous symphony 'Symphony No. 6'?", 10, true, true, "Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Johannes Brahms", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead singer of the band U2?", 10, true, true, "Bono", "The Edge", "Adam Clayton", "Larry Mullen Jr.", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'Les Demoiselles d'Avignon'?", 10, true, true, "Pablo Picasso", "Vincent van Gogh", "Édouard Manet", "Henri Matisse", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous piano composition 'Nocturne in E-Flat Major'?", 10, true, true, "Frédéric Chopin", "Ludwig van Beethoven", "Johannes Brahms", "Franz Liszt", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the novel 'The Catcher in the Rye'?", 10, true, true, "J.D. Salinger", "Ernest Hemingway", "F. Scott Fitzgerald", "Mark Twain", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'Sunflowers'?", 10, true, true, "Vincent van Gogh", "Claude Monet", "Pablo Picasso", "Salvador Dalí", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous ballet 'Giselle'?", 10, true, true, "Adolphe Adam", "Pyotr Ilyich Tchaikovsky", "Léo Delibes", "Sergei Prokofiev", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead guitarist of the band Pink Floyd?", 10, true, true, "David Gilmour", "Syd Barrett", "Roger Waters", "Nick Mason", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Night Watch'?", 10, true, true, "Rembrandt", "Johannes Vermeer", "Jan van Eyck", "Hieronymus Bosch", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous opera 'Don Giovanni'?", 10, true, true, "Wolfgang Amadeus Mozart", "Giacomo Puccini", "Richard Wagner", "Giuseppe Verdi", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead vocalist of the band AC/DC?", 10, true, true, "Brian Johnson", "Bon Scott", "Angus Young", "Cliff Williams", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Girl with the Pearl Earring'?", 10, true, true, "Johannes Vermeer", "Rembrandt", "Vincent van Gogh", "Édouard Manet", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous piano composition 'Études'?", 10, true, true, "Frédéric Chopin", "Ludwig van Beethoven", "Johannes Brahms", "Franz Liszt", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the play 'A Streetcar Named Desire'?", 10, true, true, "Tennessee Williams", "Arthur Miller", "Eugene O'Neill", "Samuel Beckett", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Thinker'?", 10, true, true, "Auguste Rodin", "Pablo Picasso", "Vincent van Gogh", "Edvard Munch", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous ballet 'The Nutcracker'?", 10, true, true, "Pyotr Ilyich Tchaikovsky", "Claude Debussy", "Sergei Prokofiev", "Igor Stravinsky", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the novel '1984'?", 10, true, true, "George Orwell", "Aldous Huxley", "Ray Bradbury", "Jules Verne", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous opera 'Madama Butterfly'?", 10, true, true, "Giacomo Puccini", "Wolfgang Amadeus Mozart", "Richard Wagner", "Giuseppe Verdi", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead vocalist of the band Aerosmith?", 10, true, true, "Steven Tyler", "Joe Perry", "Tom Hamilton", "Joey Kramer", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Birth of Venus'?", 10, true, true, "Sandro Botticelli", "Leonardo da Vinci", "Raphael", "Michelangelo", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous ballet 'La Bayadère'?", 10, true, true, "Ludwig Minkus", "Sergei Prokofiev", "Aram Khachaturian", "Igor Stravinsky", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the novel 'One Hundred Years of Solitude'?", 10, true, true, "Gabriel García Márquez", "Isabel Allende", "Mario Vargas Llosa", "Jorge Luis Borges", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Creation of Adam'?", 10, true, true, "Michelangelo", "Leonardo da Vinci", "Raphael", "Caravaggio", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous opera 'The Marriage of Figaro'?", 10, true, true, "Wolfgang Amadeus Mozart", "Giacomo Puccini", "Richard Wagner", "Giuseppe Verdi", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead guitarist of the band Red Hot Chili Peppers?", 10, true, true, "John Frusciante", "Hillel Slovak", "Josh Klinghoffer", "Dave Navarro", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Persistence of Memory'?", 10, true, true, "Salvador Dalí", "Pablo Picasso", "Vincent van Gogh", "Edvard Munch", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous symphony 'Symphony No. 9'?", 10, true, true, "Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Franz Schubert", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the play 'The Crucible'?", 10, true, true, "Arthur Miller", "Tennessee Williams", "Eugene O'Neill", "Samuel Beckett", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'American Gothic'?", 10, true, true, "Grant Wood", "Edward Hopper", "Georgia O'Keeffe", "Jackson Pollock", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous opera 'Rigoletto'?", 10, true, true, "Giuseppe Verdi", "Wolfgang Amadeus Mozart", "Richard Wagner", "Giacomo Puccini", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead vocalist of the band The Doors?", 10, true, true, "Jim Morrison", "Ray Manzarek", "Robby Krieger", "John Densmore", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'Les Demoiselles d'Avignon'?", 10, true, true, "Pablo Picasso", "Vincent van Gogh", "Édouard Manet", "Henri Matisse", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous piano composition 'Nocturne in E-Flat Major'?", 10, true, true, "Frédéric Chopin", "Ludwig van Beethoven", "Johannes Brahms", "Franz Liszt", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the play 'A Streetcar Named Desire'?", 10, true, true, "Tennessee Williams", "Arthur Miller", "Eugene O'Neill", "Samuel Beckett", "Art/Music"),

            // Sport

            new WildCardProperties("Quiz! In which city is the AFL Grand Final traditionally held?", 10, true, true, "Melbourne", "Sydney", "Brisbane", "Perth", "Sport"),
            new WildCardProperties("Quiz! What is the maximum number of players allowed on the field for each team in AFL?", 10, true, true, "18", "16", "20", "22", "Sport"),
            new WildCardProperties("Quiz! Which team has won the most AFL premierships?", 10, true, true, "Essendon", "Collingwood", "Carlton", "Hawthorn", "Sport"),
            new WildCardProperties("Quiz! What is the AFL's highest individual award for players?", 10, true, true, "Brownlow Medal", "Norm Smith Medal", "Coleman Medal", "Shearer Medal", "Sport"),
            new WildCardProperties("Quiz! Which team is known as the 'Mighty Hawks' in the AFL?", 10, true, true, "Hawthorn", "Geelong", "Richmond", "Adelaide", "Sport"),
            new WildCardProperties("Quiz! What is the shape of the ball used in AFL?", 10, true, true, "Oval", "Round", "Hexagonal", "Spherical", "Sport"),
            new WildCardProperties("Quiz! Which team won the 2021 AFL Grand Final?", 10, true, true, "Western Bulldogs", "Geelong Cats", "Port Adelaide", "Brisbane Lions", "Sport"),
            new WildCardProperties("Quiz! How many points is a goal worth in AFL?", 10, true, true, "6", "5", "7", "8", "Sport"),
            new WildCardProperties("Quiz! Which team was the first-ever premiership winner of the AFL?", 10, true, true, "Carlton", "Collingwood", "Essendon", "Hawthorn", "Sport"),
            new WildCardProperties("Quiz! In which year was the AFL established?", 10, true, true, "1897", "1900", "1879", "1920", "Sport"),
            new WildCardProperties("Quiz! How many players are on the field for each team in a standard soccer match?", 10, true, true, "11", "10", "9", "12", "Sport"),
            new WildCardProperties("Quiz! Who won the FIFA World Cup in 2018?", 10, true, true, "France", "Croatia", "Brazil", "Germany", "Sport"),
            new WildCardProperties("Quiz! Which country is known for having the most passionate soccer fans, who are called 'Ultras'?", 10, true, true, "Italy", "Spain", "Argentina", "England", "Sport"),
            new WildCardProperties("Quiz! Who is the all-time leading goal scorer in men's international soccer?", 10, true, true, "Ali Daei", "Cristiano Ronaldo", "Lionel Messi", "Pele", "Sport"),
            new WildCardProperties("Quiz! Which famous soccer player is known as 'CR7'?", 10, true, true, "Cristiano Ronaldo", "Lionel Messi", "Neymar", "Zlatan Ibrahimovic", "Sport"),
            new WildCardProperties("Quiz! What is the name of the famous soccer tournament between European club teams?", 10, true, true, "UEFA Champions League", "Europa League", "Premier League", "La Liga", "Sport"),
            new WildCardProperties("Quiz! Which country hosted the 2014 FIFA World Cup?", 10, true, true, "Brazil", "Germany", "Russia", "South Africa", "Sport"),
            new WildCardProperties("Quiz! Which club has won the most UEFA Champions League titles?", 10, true, true, "Real Madrid", "Barcelona", "Bayern Munich", "Liverpool", "Sport"),
            new WildCardProperties("Quiz! What is the nickname of the Argentina national soccer team?", 10, true, true, "Albiceleste", "La Celeste", "Los Cafeteros", "Seleção", "Sport"),
            new WildCardProperties("Quiz! Who won the Ballon d'Or in 2021?", 10, true, true, "Lionel Messi", "Cristiano Ronaldo", "Robert Lewandowski", "Karim Benzema", "Sport"),
            new WildCardProperties("Quiz! How many players are there in a full cricket team?", 10, true, true, "11", "12", "10", "9", "Sport"),
            new WildCardProperties("Quiz! What is the highest individual score by a batsman in a Test cricket match?", 10, true, true, "400 not out", "300 not out", "350 not out", "500 not out", "Sport"),
            new WildCardProperties("Quiz! Which country won the ICC Cricket World Cup in 2019?", 10, true, true, "England", "India", "Australia", "New Zealand", "Sport"),
            new WildCardProperties("Quiz! What is the name of the famous cricket stadium in India known as the 'Eden Gardens'?", 10, true, true, "Kolkata", "Mumbai", "Delhi", "Chennai", "Sport"),
            new WildCardProperties("Quiz! How many balls are bowled in one over in cricket?", 10, true, true, "6", "4", "5", "8", "Sport"),
            new WildCardProperties("Quiz! Which country has won the most ICC Cricket World Cup titles?", 10, true, true, "Australia", "India", "England", "West Indies", "Sport"),
            new WildCardProperties("Quiz! What is the name of the traditional rivalry cricket series between England and Australia?", 10, true, true, "The Ashes", "The Battle", "The Clash", "The Encounter", "Sport"),
            new WildCardProperties("Quiz! Who is the leading run-scorer in international cricket (combined formats)?", 10, true, true, "Sachin Tendulkar", "Ricky Ponting", "Virat Kohli", "Brian Lara", "Sport"),
            new WildCardProperties("Quiz! In which country did T20 cricket originate?", 10, true, true, "England", "India", "Australia", "South Africa", "Sport"),
            new WildCardProperties("Quiz! How many players from the fielding team are allowed on the leg side during a delivery in cricket?", 10, true, true, "5", "6", "4", "3", "Sport"),
            new WildCardProperties("Quiz! Which athlete is known as the 'Fastest Man on Earth'?", 10, true, true, "Usain Bolt", "Carl Lewis", "Jesse Owens", "Tyson Gay", "Sport"),
            new WildCardProperties("Quiz! How many players are on a basketball team?", 10, true, true, "5", "6", "7", "8", "Sport"),
            new WildCardProperties("Quiz! In which sport can you perform a 'slam dunk'?", 10, true, true, "Basketball", "Volleyball", "Tennis", "Soccer", "Sport"),
            new WildCardProperties("Quiz! What is the name of the annual international tennis tournament held in England?", 10, true, true, "Wimbledon", "French Open", "US Open", "Australian Open", "Sport"),
            new WildCardProperties("Quiz! Which country won the Rugby World Cup in 2019?", 10, true, true, "South Africa", "New Zealand", "England", "Australia", "Sport"),
            new WildCardProperties("Quiz! What is the highest possible break in snooker?", 10, true, true, "147", "154", "155", "150", "Sport"),
            new WildCardProperties("Quiz! Which country hosted the 2016 Summer Olympics?", 10, true, true, "Brazil", "USA", "China", "Russia", "Sport"),
            new WildCardProperties("Quiz! What is the diameter of a standard basketball hoop?", 10, true, true, "18 inches", "20 inches", "16 inches", "22 inches", "Sport"),
            new WildCardProperties("Quiz! How many players are there on a field hockey team?", 10, true, true, "11", "12", "10", "9", "Sport"),
            new WildCardProperties("Quiz! Which athlete has won the most Olympic gold medals in history?", 10, true, true, "Michael Phelps", "Usain Bolt", "Larisa Latynina", "Paavo Nurmi", "Sport"),
            new WildCardProperties("Quiz! Who is the all-time leading goal scorer in the history of the NBA?", 10, true, true, "Kareem Abdul-Jabbar", "Michael Jordan", "LeBron James", "Kobe Bryant", "Sport"),
            new WildCardProperties("Quiz! Which country hosted the 2019 ICC Cricket World Cup?", 10, true, true, "England", "India", "Australia", "South Africa", "Sport"),
            new WildCardProperties("Quiz! How many players are there on a rugby union team?", 10, true, true, "15", "11", "13", "17", "Sport"),
            new WildCardProperties("Quiz! Who won the Formula 1 Drivers' World Championship in 2021?", 10, true, true, "Lewis Hamilton", "Max Verstappen", "Sebastian Vettel", "Valtteri Bottas", "Sport"),
            new WildCardProperties("Quiz! In which city is the headquarters of the International Olympic Committee (IOC) located?", 10, true, true, "Lausanne", "Geneva", "Zurich", "Bern", "Sport"),
            new WildCardProperties("Quiz! Which country has won the most FIFA Women's World Cup titles?", 10, true, true, "United States", "Germany", "Norway", "Brazil", "Sport"),
            new WildCardProperties("Quiz! What is the name of the famous horse race that takes place annually in the United Kingdom?", 10, true, true, "The Grand National", "The Kentucky Derby", "The Melbourne Cup", "The Preakness Stakes", "Sport"),
            new WildCardProperties("Quiz! Who is the only tennis player to achieve the Golden Slam (winning all four Grand Slam titles and Olympic gold)?", 10, true, true, "Steffi Graf", "Serena Williams", "Roger Federer", "Rafael Nadal", "Sport"),
            new WildCardProperties("Quiz! Which team has won the most Super Bowl championships in NFL history?", 10, true, true, "Pittsburgh Steelers", "New England Patriots", "San Francisco 49ers", "Dallas Cowboys", "Sport"),
            new WildCardProperties("Quiz! What sport did Lola Bunny play in Space Jam?", 10, true, true, "Basketball", "Soccer", "Golf", "Tennis", "Sport"),

            // Movies

            new WildCardProperties("Quiz! Which 1994 movie features a mysterious briefcase that emits a golden light?", 10, true, true, "Pulp Fiction", "The Shawshank Redemption", "The Lion King", "Forrest Gump", "Movies"),
            new WildCardProperties("Quiz! In the movie 'Blade Runner', what is the term used for humanoid robots?", 10, true, true, "Replicants", "Synthetics", "Humanoids", "Androids", "Movies"),
            new WildCardProperties("Quiz! Which 1982 science fiction film involves a young boy who befriends an alien stranded on Earth?", 10, true, true, "E.T. the Extra-Terrestrial", "Blade Runner", "Tron", "The Thing", "Movies"),
            new WildCardProperties("Quiz! What is the name of the virtual reality world in the movie 'Ready Player One'?", 10, true, true, "OASIS", "The Grid", "The Matrix", "The Net", "Movies"),
            new WildCardProperties("Quiz! Which movie features a former assassin seeking revenge for the death of his dog?", 10, true, true, "John Wick", "Taken", "The Equalizer", "Kill Bill", "Movies"),
            new WildCardProperties("Quiz! In 'The Silence of the Lambs', what is the nickname of the serial killer being pursued?", 10, true, true, "Buffalo Bill", "The Zodiac Killer", "The Night Stalker", "The Ripper", "Movies"),
            new WildCardProperties("Quiz! Which movie follows the story of a jazz musician who falls in love with an actress?", 10, true, true, "La La Land", "Whiplash", "Birdman", "The Artist", "Movies"),
            new WildCardProperties("Quiz! Who directed the movie 'Fight Club'?", 10, true, true, "David Fincher", "Quentin Tarantino", "Martin Scorsese", "Christopher Nolan", "Movies"),
            new WildCardProperties("Quiz! In the film 'Inglourious Basterds', what is the nickname of the Nazi officer who becomes the target of the Basterds?", 10, true, true, "The Jew Hunter", "The Gestapo Butcher", "The Fuhrer's Fist", "The Iron Eagle", "Movies"),
            new WildCardProperties("Quiz! Which movie features a mentally challenged man with an IQ of 75?", 10, true, true, "Forrest Gump", "Rain Man", "A Beautiful Mind", "Good Will Hunting", "Movies"),
            new WildCardProperties("Quiz! Who played the character of Lisbeth Salander in the movie 'The Girl with the Dragon Tattoo' (2011)?", 10, true, true, "Rooney Mara", "Noomi Rapace", "Scarlett Johansson", "Emma Stone", "Movies"),
            new WildCardProperties("Quiz! What is the name of the mysterious island theme park in 'Jurassic Park'?", 10, true, true, "Isla Nublar", "Isla Sorna", "Isla Muerta", "Isla Pena", "Movies"),
            new WildCardProperties("Quiz! Which movie is about a magician duo battling each other in the late 1800s?", 10, true, true, "The Prestige", "The Illusionist", "Now You See Me", "The Great Buck Howard", "Movies"),
            new WildCardProperties("Quiz! Who portrayed the character of Anton Chigurh in the movie 'No Country for Old Men'?", 10, true, true, "Javier Bardem", "Tommy Lee Jones", "Josh Brolin", "Woody Harrelson", "Movies"),
            new WildCardProperties("Quiz! Which movie involves a group of astronauts trying to survive on a desolate planet after a dust storm?", 10, true, true, "The Martian", "Gravity", "Interstellar", "Apollo 13", "Movies"),
            new WildCardProperties("Quiz! In the film 'Oldboy', what is the main character's quest for vengeance fueled by?", 10, true, true, "Revenge for his daughter", "Seeking justice for his wife", "Punishment for betrayal", "Redemption for his past", "Movies"),
            new WildCardProperties("Quiz! Which movie is based on the true story of a man who spends years searching for the meaning of a cryptic message?", 10, true, true, "The Da Vinci Code", "National Treasure", "The Ninth Gate", "Angels & Demons", "Movies"),
            new WildCardProperties("Quiz! Who directed the movie 'Interstellar'?", 10, true, true, "Christopher Nolan", "Denis Villeneuve", "Steven Spielberg", "Alfonso Cuarón", "Movies"),
            new WildCardProperties("Quiz! In the film 'Donnie Darko', what is the name of Donnie's imaginary friend?", 10, true, true, "Frank", "Harvey", "Sam", "Max", "Movies"),
            new WildCardProperties("Quiz! Which movie features a group of magicians known as 'The Four Horsemen' performing heists during their shows?", 10, true, true, "Now You See Me", "The Prestige", "The Illusionist", "Oceans Eleven", "Movies"),
            new WildCardProperties("Quiz! Who played the role of Clarice Starling in the movie 'The Silence of the Lambs'?", 10, true, true, "Jodie Foster", "Julianne Moore", "Halle Berry", "Sigourney Weaver", "Movies"),
            new WildCardProperties("Quiz! What is the name of the AI system that runs the spaceship in '2001: A Space Odyssey'?", 10, true, true, "HAL 9000", "GLaDOS", "C-3PO", "R2-D2", "Movies"),
            new WildCardProperties("Quiz! Which movie is about a man who experiences time backward from the moment of his death?", 10, true, true, "The Curious Case of Benjamin Button", "Memento", "Inception", "Eternal Sunshine of the Spotless Mind", "Movies"),
            new WildCardProperties("Quiz! In 'The Matrix', what is the name of the virtual reality world where most humans live?", 10, true, true, "The Matrix", "The Oasis", "The Grid", "The Net", "Movies"),
            new WildCardProperties("Quiz! What is the name of the fictional African kingdom in 'Black Panther'?", 10, true, true, "Wakanda", "Zamunda", "Genovia", "Agrabah", "Movies"),
            new WildCardProperties("Quiz! Which movie tells the story of a mute woman who falls in love with an amphibious creature?", 10, true, true, "The Shape of Water", "Pan's Labyrinth", "Splash", "Waterworld", "Movies"),
            new WildCardProperties("Quiz! Who directed the movie 'Taxi Driver'?", 10, true, true, "Martin Scorsese", "Quentin Tarantino", "Francis Ford Coppola", "Stanley Kubrick", "Movies"),
            new WildCardProperties("Quiz! In 'The Departed', what is the alias of the undercover cop played by Leonardo DiCaprio?", 10, true, true, "Billy Costigan", "Frank Costello", "Collin Sullivan", "Jimmy Malone", "Movies"),
            new WildCardProperties("Quiz! Which movie is about a chess prodigy who becomes a grandmaster and battles addiction?", 10, true, true, "Searching for Bobby Fischer", "Pawn Sacrifice", "Queen of Katwe", "The Luzhin Defence", "Movies"),
            new WildCardProperties("Quiz! What is the name of the ship in the 'Alien' movie franchise?", 10, true, true, "Nostromo", "Prometheus", "Sulaco", "Discovery One", "Movies"),
            new WildCardProperties("Quiz! Which tv-show involves a high school teacher who starts cooking meth to secure his family's financial future?", 10, true, true, "Breaking Bad", "Sons of Anarchy", "The Sopranos", "The Wire", "Movies"),
            new WildCardProperties("Quiz! Who played the role of Patrick Bateman in the movie 'American Psycho'?", 10, true, true, "Christian Bale", "Leonardo DiCaprio", "Jared Leto", "Matt Damon", "Movies"),
            new WildCardProperties("Quiz! What is the name of the group of rebels fighting against the Empire in 'Star Wars'?", 10, true, true, "The Rebel Alliance", "The Resistance", "The Jedi Order", "The Rebel Force", "Movies"),
            new WildCardProperties("Quiz! Which movie is based on the true story of a man who survived on a deserted island for four years?", 10, true, true, "Cast Away", "Life of Pi", "Survivor", "The Beach", "Movies"),
            new WildCardProperties("Quiz! Who directed the movie 'A Clockwork Orange'?", 10, true, true, "Stanley Kubrick", "David Lynch", "Francis Ford Coppola", "Alfred Hitchcock", "Movies"),
            new WildCardProperties("Quiz! In the film 'Se7en', what is the serial killer's motive for his gruesome murders?", 10, true, true, "The Seven Deadly Sins", "The Zodiac", "Religious Punishment", "Avenging the Past", "Movies"),
            new WildCardProperties("Quiz! Which movie features a hacker known as 'Neo' who discovers the truth about reality?", 10, true, true, "The Matrix", "Hackers", "The Net", "Swordfish", "Movies"),
            new WildCardProperties("Quiz! What is the name of the fictional African city in 'Black Panther'?", 10, true, true, "Wakanda", "Zamunda", "Genovia", "Agrabah", "Movies"),
            new WildCardProperties("Quiz! Which movie is about a man who hires two thugs to kidnap his wife in an attempt for ransom?", 10, true, true, "Fargo", "Kill Bill", "Heat", "Pulp Fiction", "Movies"),
            new WildCardProperties("Quiz! Who played the character of 'Keyser Söze' in the movie 'The Usual Suspects'?", 10, true, true, "Kevin Spacey", "Benicio Del Toro", "Gabriel Byrne", "Stephen Baldwin", "Movies"),
            new WildCardProperties("Quiz! What is the name of the computer program that creates the virtual reality world in 'The Matrix'?", 10, true, true, "The Architect", "The Oracle", "The Keymaker", "The Merovingian", "Movies"),
            new WildCardProperties("Quiz! In the film 'Drive', what is the name of the mysterious and silent stuntman and getaway driver?", 10, true, true, "Driver", "Racer", "Wheeler", "Speedster", "Movies"),
            new WildCardProperties("Quiz! Which movie is about a girl who is the lone survivor of a massacre carried out by her demented uncle?", 10, true, true, "Texas Chainsaw Massacre", "Halloween", "Friday the 13th", "Nightmare on Elm Street", "Movies"),
            new WildCardProperties("Quiz! Who directed the movie 'Apocalypse Now'?", 10, true, true, "Francis Ford Coppola", "Stanley Kubrick", "Martin Scorsese", "Steven Spielberg", "Movies"),
            new WildCardProperties("Quiz! In 'The Shining', what phrase does Jack Nicholson's character repeatedly type on his typewriter?", 10, true, true, "All work and no play makes Jack a dull boy", "Here's Johnny!", "Redrum", "Heeeere's Johnny!", "Movies"),
            new WildCardProperties("Quiz! Which 2014 movie tells the story of a man with dissociative identity disorder?", 10, true, true, "Split", "Shutter Island", "Psycho", "Identity", "Movies"),
            new WildCardProperties("Quiz! Who played the character of Don Vito Corleone in the movie 'The Godfather'?", 10, true, true, "Marlon Brando", "Al Pacino", "Robert De Niro", "James Caan", "Movies"),
            new WildCardProperties("Quiz! Which non-military movie is about a man who becomes trapped in a time loop, reliving the same day repeatedly?", 10, true, true, "Groundhog Day", "Edge of Tomorrow", "Happy Death Day", "Source Code", "Movies"),
            new WildCardProperties("Quiz! Who directed the science fiction film 'The Fifth Element'?", 10, true, true, "Luc Besson", "Michael Bay", "James Cameron", "Ridley Scott", "Movies"),

            //Video Games

            new WildCardProperties("Quiz! In the game 'The Witcher 3: Wild Hunt', what is the name of Geralt's adopted daughter?", 10, true, true, "Ciri", "Triss", "Yennefer", "Arya", "Video Games"),
            new WildCardProperties("Quiz! Which critically acclaimed video game has a protagonist named Arthur Morgan?", 10, true, true, "Red Dead Redemption 2", "Grand Theft Auto V", "The Last of Us Part II", "God of War", "Video Games"),
            new WildCardProperties("Quiz! In the 'Dark Souls' series, what is the name of the enigmatic figure who guides the player?", 10, true, true, "The Fire Keeper", "The Ashen One", "The Chosen Undead", "The Lord of Cinder", "Video Games"),
            new WildCardProperties("Quiz! Which video game is set in the dystopian city of Dunwall and features a supernatural assassin?", 10, true, true, "Dishonored", "Thief", "Deus Ex: Human Revolution", "Bioshock Infinite", "Video Games"),
            new WildCardProperties("Quiz! In 'The Legend of Zelda: Ocarina of Time', what is the name of the final boss?", 10, true, true, "Ganondorf", "Link", "Zelda", "Vaati", "Video Games"),
            new WildCardProperties("Quiz! Which video game series features the character Solid Snake?", 10, true, true, "Metal Gear Solid", "Splinter Cell", "Call of Duty", "Assassin's Creed", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the protagonist in the video game 'Celeste'?", 10, true, true, "Madeline", "Theo", "Oshiro", "Granny", "Video Games"),
            new WildCardProperties("Quiz! In the 'Dark Souls' series, what is the term used for regaining lost experience points upon death?", 10, true, true, "Bloodstain Retrieval", "Soul Transference", "Resurrection", "Spirit Reclamation", "Video Games"),
            new WildCardProperties("Quiz! Which video game series is set in the fictional city of Rapture?", 10, true, true, "BioShock", "Half-Life", "Fallout", "System Shock", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the cyber-themed video game released by CD Projekt Red in 2010?", 10, true, true, "Cyberpunk 2077", "Deus Ex: Human Revolution", "Watch Dogs", "Shadowrun", "Video Games"),
            new WildCardProperties("Quiz! In 'The Elder Scrolls V: Skyrim', what is the name of the dragon that players can summon?", 10, true, true, "Odahviing", "Paarthurnax", "Durnehviir", "Alduin", "Video Games"),
            new WildCardProperties("Quiz! Which video game features a character named Aloy who hunts robotic creatures?", 10, true, true, "Horizon Zero Dawn", "Nier: Automata", "The Witcher 3: Wild Hunt", "God of War", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the criminal organization in the video game 'Grand Theft Auto V'?", 10, true, true, "The Merryweather Security Consulting", "The Diamond Casino & Resort", "Los Santos Vagos", "The Lost MC", "Video Games"),
            new WildCardProperties("Quiz! In the 'Dark Souls' series, what is the term used for defeating a boss without taking damage?", 10, true, true, "No-Hit Run", "Perfect Battle", "Flawless Victory", "Untouched Encounter", "Video Games"),
            new WildCardProperties("Quiz! Which video game franchise involves a protagonist named Samus Aran, who battles space pirates and aliens?", 10, true, true, "Metroid", "Star Fox", "F-Zero", "Kirby", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the kingdom that Princess Peach rules in the 'Super Mario' series?", 10, true, true, "Mushroom Kingdom", "Koopa Kingdom", "Toadstool Territory", "Yoshi's Island", "Video Games"),
            new WildCardProperties("Quiz! In the game 'Hollow Knight', what is the name of the protagonist?", 10, true, true, "The Knight", "The Wanderer", "The Silent", "The Ghost", "Video Games"),
            new WildCardProperties("Quiz! Which video game series involves a conflict between the Helghast and the Interplanetary Strategic Alliance?", 10, true, true, "Killzone", "Resistance", "Halo", "Gears of War", "Video Games"),
            new WildCardProperties("Quiz! What is the objective of the game 'Hades'?", 10, true, true, "To escape from the Underworld", "To overthrow the gods", "To summon ancient spirits", "To reclaim lost memories", "Video Games"),
            new WildCardProperties("Quiz! In the 'Resident Evil' series, what is the name of the pharmaceutical company responsible for the outbreak?", 10, true, true, "Umbrella Corporation", "Red Queen Corporation", "Crimson Horizon Corporation", "Nemesis Enterprises", "Video Games"),
            new WildCardProperties("Quiz! Which video game features a protagonist named Commander Shepard?", 10, true, true, "Mass Effect", "Halo", "Gears of War", "Dead Space", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the mysterious entity that grants the protagonist powers in 'Control'?", 10, true, true, "The Board", "The Bureau", "The Authority", "The Syndicate", "Video Games"),
            new WildCardProperties("Quiz! Which video game series involves a protagonist named Nathan Drake?", 10, true, true, "Uncharted", "Tomb Raider", "Assassin's Creed", "The Last of Us", "Video Games"),
            new WildCardProperties("Quiz! In the game 'Sekiro: Shadows Die Twice', what is the name of the one-armed shinobi?", 10, true, true, "Wolf", "Snake", "Dragon", "Ghost", "Video Games"),
            new WildCardProperties("Quiz! Which video game features a conflict between the Helghast and the Interplanetary Strategic Alliance?", 10, true, true, "Killzone", "Resistance", "Battlefield", "Gears of War", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the main character in the 'Dead Space' video game series?", 10, true, true, "Isaac Clarke", "Ethan Winters", "Sebastian Castellanos", "Leon Kennedy", "Video Games"),
            new WildCardProperties("Quiz! In the game 'Dark Souls III', what is the name of the firekeeper at Firelink Shrine?", 10, true, true, "Anastacia of Astora", "Gwynevere", "Emma", "Quelaag", "Video Games"),
            new WildCardProperties("Quiz! Which video game involves controlling a character named Chell, who navigates through test chambers?", 10, true, true, "Portal", "Half-Life", "Bioshock", "The Witness", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the artificial intelligence in 'Halo'?", 10, true, true, "Cortana", "Athena", "Hera", "Vera", "Video Games"),
            new WildCardProperties("Quiz! In the 'NieR' series, what is the name of the protagonist who seeks to save his daughter?", 10, true, true, "Nier", "Automata", "Adam", "Eve", "Video Games"),
            new WildCardProperties("Quiz! Which video game franchise is set in the post-apocalyptic world of Sera?", 10, true, true, "Gears of War", "Fallout", "Resident Evil", "The Last of Us", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the protagonist in the 'Hitman' video game series?", 10, true, true, "Agent 47", "Max Payne", "Jason Bourne", "John Wick", "Video Games"),
            new WildCardProperties("Quiz! In 'Celeste', what is the name of the mountain the protagonist climbs?", 10, true, true, "Mount Celeste", "Mount Olympus", "Mount Everest", "Mount Kilimanjaro", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the protagonist in the game 'Hollow Knight'?", 10, true, true, "The Knight", "The Wanderer", "The Silencer", "The Shadow", "Video Games"),
            new WildCardProperties("Quiz! In 'Metal Gear Solid 3: Snake Eater', what is the name of the main antagonist?", 10, true, true, "Volgin", "Liquid Snake", "Revolver Ocelot", "The Boss", "Video Games"),
            new WildCardProperties("Quiz! Which video game features a character named Kratos, who seeks revenge against the gods?", 10, true, true, "God of War", "Titanfall", "Doom", "Assassin's Creed", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the protagonist in the video game 'Bloodborne'?", 10, true, true, "The Hunter", "The Slayer", "The Reaper", "The Stalker", "Video Games"),
            new WildCardProperties("Quiz! In the game 'Control', what is the name of the government agency investigating paranatural phenomena?", 10, true, true, "Federal Bureau of Control", "Central Bureau of Investigation", "Department of Paranormal Affairs", "Bureau of Supernatural Research", "Video Games"),
            new WildCardProperties("Quiz! In the video game 'Nier: Automata', what is the name of the android protagonist battling against the machines?", 10, true, true, "2B", "A2", "9S", "N2", "Video Games"),
            new WildCardProperties("Quiz! Which video game series features a group of elite soldiers known as the Ghosts, who carry out special operations missions?", 10, true, true, "Tom Clancy's Ghost Recon", "Splinter Cell", "Rainbow Six", "Call of Duty", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the sentient AI construct in the 'Halo' series that serves as the main antagonist?", 10, true, true, "The Didact", "Cortana", "343 Guilty Spark", "Mendicant Bias", "Video Games"),
            new WildCardProperties("Quiz! In 'The Legend of Zelda: Breath of the Wild', what is the name of the kingdom that was destroyed 100 years before the events of the game?", 10, true, true, "Hyrule", "Zora's Domain", "Gerudo Desert", "Kakariko Village", "Video Games"),
            new WildCardProperties("Quiz! Which video game series follows the adventures of a young man named Link, who must rescue Princess Zelda from the evil villain Ganon?", 10, true, true, "The Legend of Zelda", "Metroid", "Super Mario", "Final Fantasy", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the main antagonist in the 'Assassin's Creed' series, an ancient organization seeking control over humanity?", 10, true, true, "The Templars (Order of the Knights Templar)", "The Assassins", "The Order of Ancients", "The Brotherhood", "Video Games"),
            new WildCardProperties("Quiz! In the game 'Final Fantasy VII', what is the name of the villain who seeks to destroy the planet by summoning a meteor?", 10, true, true, "Sephiroth", "Kefka Palazzo", "Ultimecia", "Kuja", "Video Games"),
            new WildCardProperties("Quiz! Which video game series features a protagonist named Ezio Auditore da Firenze, who seeks revenge against the Templar Order?", 10, true, true, "Assassin's Creed II", "Prince of Persia", "Hitman", "Splinter Cell", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the AI companion that assists the player in 'Half-Life 2' and becomes a key character in the series?", 10, true, true, "Alyx Vance", "Dog", "G-Man", "Barney Calhoun", "Video Games"),
            new WildCardProperties("Quiz! In the game 'The Last of Us', what is the name of the fungal infection that has devastated the world and turned humans into hostile creatures?", 10, true, true, "Cordyceps Brain Infection (CBI)", "Zombivirus", "Infected Parasite Strain (IPS)", "Mutagen-X", "Video Games"),
            new WildCardProperties("Quiz! Which video game series involves a fictional war between the Helghan Empire and the Interplanetary Strategic Alliance?", 10, true, true, "Killzone", "Resistance", "Red Faction", "Borderlands", "Video Games")
    };


    public static final WildCardProperties[] EXTRA_WILD_CARDS = {
            new WildCardProperties("Double the current number!", 10, true, false),
            new WildCardProperties("Half the current number!", 10, true, false),
            new WildCardProperties("Reset the number!", 10, true, false),
            new WildCardProperties("Reverse the turn order!", 10, true, false),
            new WildCardProperties("Gain a couple more wildcards to use, I gotchya back!", 10, true, false),
            new WildCardProperties("Lose a couple wildcards\n\n:( oh also drink 3 lol!", 10, true, false),
    };

    public static final WildCardProperties[] TASK_WILD_CARDS = {
            new WildCardProperties("Task! Take 1 drink.", 10, true, true),
            new WildCardProperties("Task! Take 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Take 3 drinks.", 10, true, true),
            new WildCardProperties("Task! Finish your drink.", 10, true, true),
            new WildCardProperties("Task! Give 1 drink.", 10, true, true),
            new WildCardProperties("Task! Give 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Give 3 drinks.", 10, true, true),
            new WildCardProperties("Task! Choose a player to finish their drink.", 10, true, true),
            new WildCardProperties("Task! The player to the left takes a drink.", 10, true, true),
            new WildCardProperties("Task! The player to the right takes a drink.", 10, true, true),
            new WildCardProperties("Task! The oldest player takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! The youngest player takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! The player who last peed takes 3 drinks.", 10, true, true),
            new WildCardProperties("Task! The player with the oldest car takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Whoever last rode on a train takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Anyone who is standing takes 4 drinks, why are you standing? Sit down mate.", 10, true, true),
            new WildCardProperties("Task! Anyone who is sitting takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Whoever has the longest hair takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Whoever is wearing a watch takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Whoever has a necklace on takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Double the ending drink (whoever loses must now do double the consequence).", 10, true, true),
            new WildCardProperties("Task! Have a drink for courage, then deliver a line from your favourite film making it as dramatic as possible!", 10, true, true),
            new WildCardProperties("Task! Give 1 drink for every cheese you can name in 10 seconds.", 10, true, true),
            new WildCardProperties("Task! The shortest person at the table must take 4 drinks then give 4 drinks.", 10, true, true),
            new WildCardProperties("Task! Bare your biceps and flex for everyone. The players next to you each drink 2 for the view.", 10, true, true),
            new WildCardProperties("Task! All females drink 3, and all males drink 3. Equality.", 10, true, true),
            new WildCardProperties("Task! Do a handstand and give out 3 drinks.", 10, true, true),
            new WildCardProperties("Task! Choose someone to drink with their non-dominant hand for the next round.", 10, true, true),
            new WildCardProperties("Task! The next person to laugh must take 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Everyone must not put their elbows on the table for the rest of the game, if you do, take a drink.", 10, true, true),
            new WildCardProperties("Task! Recite the alphabet backward in 10 seconds. Give out drinks for each correct letter before making a mistake or time running out.", 10, true, true),
            new WildCardProperties("Task! You can only drink while making eye contact with someone for the rest of the game.", 10, true, true),
            new WildCardProperties("Task! The person with the longest fingernails takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! The person with the most expensive item on them takes 3 drinks.", 10, true, true),
            new WildCardProperties("Task! The person with the most keys takes 3 drinks.", 10, true, true),
            new WildCardProperties("Task! The person with the longest beard takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Choose someone to take 2 drinks and perform a dance move.", 10, true, true),
            new WildCardProperties("Task! Take a drink for each person with brown eyes in the group.", 10, true, true),
            new WildCardProperties("Task! If you can touch your tongue to the tip of your nose give out 2 drinks, if you can’t take 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Take a drink while doing a split.", 10, true, true),
            new WildCardProperties("Task! Give a toast to the person whos house you are in and take a drink.", 10, true, true),
            new WildCardProperties("Task! The person wearing the most buttons on their shirt takes 3 drinks. Mr Fancy aye.", 10, true, true),
            new WildCardProperties("Task! The person with the most watches takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Give 2 drinks to someone, and serenade that person.", 10, true, true),
            new WildCardProperties("Task! Impersonate your favourite celebrity. Others guess who it is. If they fail, they drink.", 10, true, true),
            new WildCardProperties("Task! Play a round of categories, (your choice of the category) loser takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Give out 2 drinks for each double joint you have, take 2 drinks if you don’t have any.", 10, true, true),
            new WildCardProperties("Task! Tell a cheesy joke. If others laugh, you're safe. If not, take 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Draw a picture blindfolded. Others rate your masterpiece. If the crowd does not like it, take 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Name something that should be illegal but aren't. If others agree, you're safe, if not, you take 3 drinks.", 10, true, true),
    };


    public static final WildCardProperties[] TRUTH_WILD_CARDS = {
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on a friend's significant other.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a one-night stand.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever kissed someone of the same gender.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever sent accidentally sent a nude to someone you weren’t meant to.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever used a dating app to stalk someone.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a friends-with-benefits arrangement.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever used online chat room sex calls.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever been offered a sugga daddy/mommy situation.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever skinny-dipped in the ocean or a natural body of water.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a romantic dream about someone in this room.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever made out with a photograph of a celebrity.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever used a dating app while already in a relationship.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a secret admirer.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a steamy hookup in a public place.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on someone in this room.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever kissed someone within minutes of meeting them.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever engaged in role-playing with a partner.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a wardrobe malfunction in public.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a regrettable tattoo.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever drunk called an ex.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on a co-worker.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever lied about your age to someone.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex on a beach.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on a cartoon character.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex, and it ended in a trip to a medical room.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever been offered money for sex. Give out 5 drinks if you have taken the offer.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on a friend's sibling.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever flirted with a teacher or boss.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a romantic encounter during a vacation.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever watched adult content in a public place.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a one-night stand while travelling.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had pretended your sexual partner was a fictional character.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever lied about your relationship status.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex on a rooftop.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on a neighbour.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex on a boat.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever flirted with someone much older or younger than you.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex in a car.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever simped for a social media influencer, and sent them a message.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a steamy chat with a stranger online.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex in a public restroom.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on a friend's ex-partner.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever received a risqué text from the wrong person.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on your boss.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex in the rain.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex/masturbated at work.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex during a festival.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex/masturbated at school.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a provocative photoshoot.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex in an elevator.", 10, true, true),

    };
}
