package com.example.countingdowngame.wildCards.wildCardTypes;

import com.example.countingdowngame.wildCards.WildCardProperties;

public class WildCardData {
    public static final WildCardProperties[] QUIZ_WILD_CARDS = {
            // Science Quiz Questions
            new WildCardProperties("Quiz! What is the deepest ocean on Earth?", 10, true, true, "Pacific Ocean", "Science"),
            new WildCardProperties("Quiz! How many legs does a spider have?", 10, true, true, "8", "Science"),
            new WildCardProperties("Quiz! How many sides does a heptagon have?", 10, true, true, "7", "Science"),
            new WildCardProperties("Quiz! What is the largest planet in our solar system?", 10, true, true, "Jupiter", "Science"),
            new WildCardProperties("Quiz! Can you name all seven colors of the rainbow in order?", 10, true, true, "Red, Orange, Yellow, Green, Blue, Indigo, Violet", "Science"),
            new WildCardProperties("Quiz! What is the formula for calculating the area of a circle?", 10, true, true, "πr^2", "Science"),
            new WildCardProperties("Quiz! What is the boiling point of water in Fahrenheit?", 10, true, true, "212", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for silver on the periodic table?", 10, true, true, "Ag", "Science"),
            new WildCardProperties("Quiz! What is the chemical formula for glucose?", 10, true, true, "C6H12O6", "Science"),
            new WildCardProperties("Quiz! How many chromosomes are in a human body cell?", 10, true, true, "46", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for helium on the periodic table?", 10, true, true, "He", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for oxygen on the periodic table?", 10, true, true, "O", "Science"),
            new WildCardProperties("Quiz! What is the boiling point of water in Celsius?", 10, true, true, "100", "Science"),
            new WildCardProperties("Quiz! Who developed the theory of general relativity?", 10, true, true, "Albert Einstein", "Science"),
            new WildCardProperties("Quiz! What is the atomic number of hydrogen?", 10, true, true, "1", "Science"),
            new WildCardProperties("Quiz! What is the largest organ in the human body?", 10, true, true, "Skin", "Science"),
            new WildCardProperties("Quiz! How many chromosomes are in a human body cell?", 10, true, true, "46", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for helium on the periodic table?", 10, true, true, "He", "Science"),
            new WildCardProperties("Quiz! Who discovered penicillin?", 10, true, true, "Alexander Fleming", "Science"),
            new WildCardProperties("Quiz! What is the formula for calculating the area of a circle?", 10, true, true, "πr^2", "Science"),
            new WildCardProperties("Quiz! What is the largest species of shark?", 10, true, true, "Whale Shark", "Science"),
            new WildCardProperties("Quiz! What is the boiling point of water in Fahrenheit?", 10, true, true, "212", "Science"),
            new WildCardProperties("Quiz! Who is known as the 'father of modern chemistry'?", 10, true, true, "Antoine Lavoisier", "Science"),
            new WildCardProperties("Quiz! What is the formula for calculating density?", 10, true, true, "Density = Mass / Volume", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for iron on the periodic table?", 10, true, true, "Fe", "Science"),
            new WildCardProperties("Quiz! Who proposed the theory of evolution by natural selection?", 10, true, true, "Charles Darwin", "Science"),
            new WildCardProperties("Quiz! What is the largest moon in the solar system?", 10, true, true, "Ganymede", "Science"),
            new WildCardProperties("Quiz! What is the freezing point of water in Celsius?", 10, true, true, "0", "Science"),
            new WildCardProperties("Quiz! Who discovered the law of gravity?", 10, true, true, "Isaac Newton", "Science"),
            new WildCardProperties("Quiz! What is the chemical formula for glucose?", 10, true, true, "C6H12O6", "Science"),
            new WildCardProperties("Quiz! Who invented the first practical telephone?", 10, true, true, "Alexander Graham Bell", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for sodium on the periodic table?", 20, true, true, "Na", "Science"),
            new WildCardProperties("Quiz! What is the process by which plants release water vapor through their leaves?", 20, true, true, "Transpiration", "Science"),
            new WildCardProperties("Quiz! What is the unit of measurement for energy?", 20, true, true, "Joule (J)", "Science"),
            new WildCardProperties("Quiz! What is the hardest substance in the human body?", 20, true, true, "Tooth enamel", "Science"),
            new WildCardProperties("Quiz! What is the chemical formula for sulfuric acid?", 20, true, true, "H2SO4", "Science"),
            new WildCardProperties("Quiz! What is the process of a gas turning into a liquid?", 20, true, true, "Condensation", "Science"),
            new WildCardProperties("Quiz! Which gas makes up about 78% of the Earth's atmosphere?", 20, true, true, "Nitrogen (N2)", "Science"),
            new WildCardProperties("Quiz! What is the unit of measurement for frequency?", 20, true, true, "Hertz (Hz)", "Science"),
            new WildCardProperties("Quiz! What is the process of a solid turning directly into a gas?", 20, true, true, "Sublimation", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for copper on the periodic table?", 20, true, true, "Cu", "Science"),
            new WildCardProperties("Quiz! What is the name for the study of fossils?", 20, true, true, "Paleontology", "Science"),
            new WildCardProperties("Quiz! What is the unit of measurement for electric potential difference?", 20, true, true, "Volt (V)", "Science"),
            new WildCardProperties("Quiz! Which gas do humans exhale during respiration?", 20, true, true, "Carbon dioxide (CO2)", "Science"),
            new WildCardProperties("Quiz! What is the process of a liquid turning into a solid?", 20, true, true, "Freezing", "Science"),
            new WildCardProperties("Quiz! What is the chemical formula for methane?", 20, true, true, "CH4", "Science"),
            new WildCardProperties("Quiz! What is the process of energy transfer through electromagnetic waves?", 20, true, true, "Radiation", "Science"),
            new WildCardProperties("Quiz! Which gas is produced during photosynthesis?", 20, true, true, "Oxygen (O2)", "Science"),
            new WildCardProperties("Quiz! What is the unit of measurement for electric resistance?", 20, true, true, "Ohm (Ω)", "Science"),
            new WildCardProperties("Quiz! What is the process of a liquid turning into a gas below its boiling point?", 20, true, true, "Evaporation", "Science"),

// Geography Quiz Questions
            new WildCardProperties("Quiz! What is the national animal of Canada?", 10, true, true, "Beaver", "Geography"),
            new WildCardProperties("Quiz! How many time zones are there in the world?", 10, true, true, "24", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Brazil?", 10, true, true, "Brasília", "Geography"),
            new WildCardProperties("Quiz! Which country is known as the 'Land of the Rising Sun'?", 10, true, true, "Japan", "Geography"),
            new WildCardProperties("Quiz! In which continent is the Sahara Desert located?", 10, true, true, "Africa", "Geography"),
            new WildCardProperties("Quiz! What is the largest country by land area?", 10, true, true, "Russia", "Geography"),
            new WildCardProperties("Quiz! What is the highest mountain in the world?", 10, true, true, "Mount Everest", "Geography"),
            new WildCardProperties("Quiz! What is the largest ocean?", 10, true, true, "Pacific Ocean", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Australia?", 10, true, true, "Canberra", "Geography"),
            new WildCardProperties("Quiz! Which river is the longest in the world?", 10, true, true, "Nile", "Geography"),
            new WildCardProperties("Quiz! What is the official language of Japan?", 10, true, true, "Japanese", "Geography"),
            new WildCardProperties("Quiz! Which city is known as the 'Eternal City'?", 10, true, true, "Rome", "Geography"),
            new WildCardProperties("Quiz! What is the largest desert in the world?", 10, true, true, "Antarctica", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Canada?", 10, true, true, "Ottawa", "Geography"),
            new WildCardProperties("Quiz! Which country is famous for the Great Barrier Reef?", 10, true, true, "Australia", "Geography"),
            new WildCardProperties("Quiz! What is the official language of Brazil?", 10, true, true, "Portuguese", "Geography"),
            new WildCardProperties("Quiz! In which country is the Taj Mahal located?", 10, true, true, "India", "Geography"),
            new WildCardProperties("Quiz! What is the largest lake in Africa?", 10, true, true, "Lake Victoria", "Geography"),
            new WildCardProperties("Quiz! What is the currency of Japan?", 10, true, true, "Japanese yen", "Geography"),
            new WildCardProperties("Quiz! In which country is Mount Kilimanjaro located?", 10, true, true, "Tanzania", "Geography"),
            new WildCardProperties("Quiz! What is the smallest country in the world?", 10, true, true, "Vatican City", "Geography"),
            new WildCardProperties("Quiz! Which country is known for the Pyramids of Giza?", 10, true, true, "Egypt", "Geography"),
            new WildCardProperties("Quiz! Which country is the largest archipelago in the world?", 20, true, true, "Indonesia", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Spain?", 20, true, true, "Madrid", "Geography"),
            new WildCardProperties("Quiz! Which river runs through the Grand Canyon in the United States?", 20, true, true, "Colorado River", "Geography"),
            new WildCardProperties("Quiz! In which continent is the Andes mountain range located?", 20, true, true, "South America", "Geography"),
            new WildCardProperties("Quiz! What is the largest island in the Mediterranean Sea?", 20, true, true, "Sicily", "Geography"),
            new WildCardProperties("Quiz! Which African country is known as the 'Pearl of the Indian Ocean'?", 20, true, true, "Sri Lanka", "Geography"),
            new WildCardProperties("Quiz! What is the official language of Germany?", 20, true, true, "German", "Geography"),
            new WildCardProperties("Quiz! Which country is the world's leading producer of coffee?", 20, true, true, "Brazil", "Geography"),
            new WildCardProperties("Quiz! What is the smallest continent in the world?", 20, true, true, "Australia", "Geography"),
            new WildCardProperties("Quiz! Which river is known as the 'Mother River' in China?", 20, true, true, "Yangtze River", "Geography"),
            new WildCardProperties("Quiz! What is the capital of South Africa?", 20, true, true, "Pretoria", "Geography"),
            new WildCardProperties("Quiz! Which country is the Land of a Thousand Lakes?", 20, true, true, "Finland", "Geography"),
            new WildCardProperties("Quiz! In which U.S. state is the Grand Canyon located?", 20, true, true, "Arizona", "Geography"),
            new WildCardProperties("Quiz! Which country is home to the famous rock formation Uluru (Ayers Rock)?", 20, true, true, "Australia", "Geography"),
            new WildCardProperties("Quiz! What is the largest city in Canada?", 20, true, true, "Toronto", "Geography"),
            new WildCardProperties("Quiz! Which river is the longest in Europe?", 20, true, true, "Volga River", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Argentina?", 20, true, true, "Buenos Aires", "Geography"),
            new WildCardProperties("Quiz! Which country is known as the 'Land of Fire and Ice'?", 20, true, true, "Iceland", "Geography"),
            new WildCardProperties("Quiz! What is the highest waterfall in the world?", 20, true, true, "Angel Falls", "Geography"),
            new WildCardProperties("Quiz! Which city is located on two continents, Europe and Asia?", 20, true, true, "Istanbul", "Geography"),
            new WildCardProperties("Quiz! Which country is known as the 'Land of the Midnight Sun'?", 10, true, true, "Norway", "Geography"),
            new WildCardProperties("Quiz! What is the largest river in the world by discharge volume?", 10, true, true, "Amazon River", "Geography"),
            new WildCardProperties("Quiz! Which country is famous for its tulip fields and windmills?", 10, true, true, "Netherlands", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Russia?", 10, true, true, "Moscow", "Geography"),
            new WildCardProperties("Quiz! Which African country is known as the 'Pearl of Africa'?", 10, true, true, "Uganda", "Geography"),
            new WildCardProperties("Quiz! In which mountain range is Mount Everest located?", 10, true, true, "Himalayas", "Geography"),
            new WildCardProperties("Quiz! What is the largest hot desert in the world?", 10, true, true, "Sahara Desert", "Geography"),
            new WildCardProperties("Quiz! Which country is famous for the Great Wall?", 10, true, true, "China", "Geography"),


// History Quiz Questions
            new WildCardProperties("Quiz! Who is the current Prime Minister of Japan?", 10, true, true, "Yoshihide Suga", "History"),
            new WildCardProperties("Quiz! In which year did World War I begin?", 10, true, true, "1914", "History"),
            new WildCardProperties("Quiz! Who was the first President of the United States?", 10, true, true, "George Washington", "History"),
            new WildCardProperties("Quiz! In which year did the United States declare independence from Great Britain?", 10, true, true, "1776", "History"),
            new WildCardProperties("Quiz! Who was the leader of the Soviet Union during World War II?", 10, true, true, "Joseph Stalin", "History"),
            new WildCardProperties("Quiz! Who painted the Mona Lisa?", 10, true, true, "Leonardo da Vinci", "History"),
            new WildCardProperties("Quiz! In which year did the Titanic sink?", 10, true, true, "1912", "History"),
            new WildCardProperties("Quiz! Who wrote the play 'Romeo and Juliet'?", 10, true, true, "William Shakespeare", "History"),
            new WildCardProperties("Quiz! In which year did the American Civil War end?", 10, true, true, "1865", "History"),
            new WildCardProperties("Quiz! Who was the first female Prime Minister of the United Kingdom?", 10, true, true, "Margaret Thatcher", "History"),
            new WildCardProperties("Quiz! In which country was Adolf Hitler born?", 10, true, true, "Austria", "History"),
            new WildCardProperties("Quiz! What is the significance of the Magna Carta?", 10, true, true, "It established the principle of the rule of law", "History"),
            new WildCardProperties("Quiz! Who was the last pharaoh of ancient Egypt?", 10, true, true, "Cleopatra", "History"),
            new WildCardProperties("Quiz! In which year did the Berlin Wall fall?", 10, true, true, "1989", "History"),
            new WildCardProperties("Quiz! Who was the first man to walk on the moon?", 10, true, true, "Neil Armstrong", "History"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Starry Night'?", 10, true, true, "Vincent van Gogh", "History"),
            new WildCardProperties("Quiz! In which year did World War II end?", 10, true, true, "1945", "History"),
            new WildCardProperties("Quiz! Who wrote the novel 'Pride and Prejudice'?", 10, true, true, "Jane Austen", "History"),
            new WildCardProperties("Quiz! What is the significance of the Declaration of Independence?", 10, true, true, "It announced the United States' independence from Great Britain", "History"),
            new WildCardProperties("Quiz! Who was the first Emperor of Rome?", 10, true, true, "Augustus", "History"),
            new WildCardProperties("Quiz! In which year did the Renaissance begin?", 10, true, true, "14th century", "History"),
            new WildCardProperties("Quiz! Who was the founder of the Mongol Empire?", 20, true, true, "Genghis Khan", "History"),
            new WildCardProperties("Quiz! In which year did the French Revolution begin?", 20, true, true, "1789", "History"),
            new WildCardProperties("Quiz! Who was the first female pharaoh of ancient Egypt?", 20, true, true, "Hatshepsut", "History"),
            new WildCardProperties("Quiz! In which year did the Industrial Revolution start?", 20, true, true, "1760", "History"),
            new WildCardProperties("Quiz! Who was the first woman to fly solo across the Atlantic?", 20, true, true, "Amelia Earhart", "History"),
            new WildCardProperties("Quiz! In which year did the Cuban Missile Crisis occur?", 20, true, true, "1962", "History"),
            new WildCardProperties("Quiz! Who was the first African American President of the United States?", 20, true, true, "Barack Obama", "History"),
            new WildCardProperties("Quiz! In which year did the Battle of Gettysburg take place during the American Civil War?", 20, true, true, "1863", "History"),
            new WildCardProperties("Quiz! Who was the first woman to win a Nobel Prize?", 20, true, true, "Marie Curie", "History"),
            new WildCardProperties("Quiz! In which year did the Russian Revolution occur?", 20, true, true, "1917", "History"),
            new WildCardProperties("Quiz! Who was the first European explorer to reach India by sea?", 20, true, true, "Vasco da Gama", "History"),
            new WildCardProperties("Quiz! In which year did the American Revolution end?", 20, true, true, "1783", "History"),
            new WildCardProperties("Quiz! Who was the Roman general who led the conquest of Gaul?", 20, true, true, "Julius Caesar", "History"),
            new WildCardProperties("Quiz! In which year did the Treaty of Versailles end World War I?", 20, true, true, "1919", "History"),
            new WildCardProperties("Quiz! Who was the legendary king of Uruk in ancient Mesopotamia?", 20, true, true, "Gilgamesh", "History"),
            new WildCardProperties("Quiz! In which year did the American colonies declare independence from Spain?", 20, true, true, "1810", "History"),
            new WildCardProperties("Quiz! Who was the first Roman Emperor?", 20, true, true, "Augustus", "History"),
            new WildCardProperties("Quiz! In which year did the Treaty of Paris end the American Revolutionary War?", 20, true, true, "1783", "History"),
            new WildCardProperties("Quiz! Who was the leader of the Bolshevik Party during the October Revolution?", 20, true, true, "Vladimir Lenin", "History"),
            new WildCardProperties("Quiz! In which year did the Black Death (Bubonic Plague) spread across Europe?", 20, true, true, "1347", "History"),
            new WildCardProperties("Quiz! Who was the first female astronaut to travel to space?", 10, true, true, "Valentina Tereshkova", "History"),
            new WildCardProperties("Quiz! In which year did the Spanish conquistador Hernán Cortés conquer the Aztec Empire?", 10, true, true, "1521", "History"),
            new WildCardProperties("Quiz! Who was the ancient Egyptian queen who ruled alongside her husband, Pharaoh Akhenaten?", 10, true, true, "Nefertiti", "History"),
            new WildCardProperties("Quiz! In which year did the Battle of Waterloo take place, leading to the defeat of Napoleon Bonaparte?", 10, true, true, "1815", "History"),
            new WildCardProperties("Quiz! Who was the first President of the United States to be impeached?", 10, true, true, "Andrew Johnson", "History"),
            new WildCardProperties("Quiz! In which year did the Great Fire of London devastate the city?", 10, true, true, "1666", "History"),
            new WildCardProperties("Quiz! Who was the Mongol emperor who established the Yuan Dynasty in China?", 10, true, true, "Kublai Khan", "History"),
            new WildCardProperties("Quiz! In which year did the Suez Canal open, connecting the Mediterranean Sea to the Red Sea?", 10, true, true, "1869", "History"),
            new WildCardProperties("Quiz! Who was the leader of the Allied forces during World War II?", 10, true, true, "Dwight D. Eisenhower", "History"),


// Art/Music Quiz Questions
            new WildCardProperties("Quiz! How many symphonies did Ludwig van Beethoven compose?", 10, true, true, "9", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Mona Lisa'?", 10, true, true, "Leonardo da Vinci", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous symphony 'Symphony No. 9'?", 10, true, true, "Ludwig van Beethoven", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Starry Night'?", 10, true, true, "Vincent van Gogh", "Art/Music"),
            new WildCardProperties("Quiz! Who wrote the play 'Hamlet'?", 10, true, true, "William Shakespeare", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous piano composition 'Für Elise'?", 10, true, true, "Ludwig van Beethoven", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the novel 'The Picture of Dorian Gray'?", 10, true, true, "Oscar Wilde", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Last Supper'?", 10, true, true, "Leonardo da Vinci", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous ballet 'Swan Lake'?", 10, true, true, "Pyotr Ilyich Tchaikovsky", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead guitarist of the band Led Zeppelin?", 10, true, true, "Jimmy Page", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Scream'?", 10, true, true, "Edvard Munch", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous opera 'The Magic Flute'?", 10, true, true, "Wolfgang Amadeus Mozart", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the novel 'War and Peace'?", 10, true, true, "Leo Tolstoy", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'Guernica'?", 10, true, true, "Pablo Picasso", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous symphony 'Symphony No. 5'?", 10, true, true, "Ludwig van Beethoven", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead singer of the band The Rolling Stones?", 10, true, true, "Mick Jagger", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Birth of Venus'?", 10, true, true, "Sandro Botticelli", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous piano composition 'Clair de Lune'?", 10, true, true, "Claude Debussy", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the novel 'The Great Gatsby'?", 10, true, true, "F. Scott Fitzgerald", "Art/Music"),
            new WildCardProperties("Quiz! How many players are there on a soccer team?", 10, true, true, "11", "Art/Music"),
            new WildCardProperties("Quiz! Who is the Greek god of the sea?", 10, true, true, "Poseidon", "Art/Music"),
            new WildCardProperties("Quiz! How many strings does a standard violin have?", 10, true, true, "4", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead vocalist of the band Queen?", 20, true, true, "Freddie Mercury", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous opera 'Carmen'?", 20, true, true, "Georges Bizet", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead guitarist of the band Guns N' Roses?", 20, true, true, "Slash", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'Girl with a Pearl Earring'?", 20, true, true, "Johannes Vermeer", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous piano composition 'Moonlight Sonata'?", 20, true, true, "Ludwig van Beethoven", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the play 'Romeo and Juliet'?", 20, true, true, "William Shakespeare", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Creation of Adam'?", 20, true, true, "Michelangelo", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous ballet 'The Nutcracker'?", 20, true, true, "Pyotr Ilyich Tchaikovsky", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the novel 'The Da Vinci Code'?", 20, true, true, "Dan Brown", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'Water Lilies'?", 20, true, true, "Claude Monet", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous opera 'La Traviata'?", 20, true, true, "Giuseppe Verdi", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead singer of the band Aerosmith?", 20, true, true, "Steven Tyler", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Guernica'?", 20, true, true, "Pablo Picasso", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous piano composition 'Nocturne in E-flat Major'?", 20, true, true, "Frederic Chopin", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the novel 'The Lord of the Rings'?", 20, true, true, "J.R.R. Tolkien", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous opera 'The Marriage of Figaro'?", 20, true, true, "Wolfgang Amadeus Mozart", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead guitarist of the band AC/DC?", 20, true, true, "Angus Young", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Persistence of Memory'?", 20, true, true, "Salvador Dalí", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead singer of the band Coldplay?", 10, true, true, "Chris Martin", "Art/Music"),
            new WildCardProperties("Quiz! Which artist sang the song 'Crazy' and collaborated with Gnarls Barkley?", 10, true, true, "CeeLo Green", "Art/Music"),
            new WildCardProperties("Quiz! Who is the singer behind the hit 'Yeah!' featuring Lil Jon and Ludacris?", 10, true, true, "Usher", "Art/Music"),
            new WildCardProperties("Quiz! Which artist performed 'I Want It That Way' with the Backstreet Boys?", 10, true, true, "AJ McLean", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead vocalist of the band Coldplay, known for songs like 'Yellow' and 'Fix You'?", 10, true, true, "Chris Martin", "Art/Music"),
            new WildCardProperties("Quiz! Which artist released the song 'Poker Face' and is known for her unique fashion style?", 10, true, true, "Lady Gaga", "Art/Music"),
            new WildCardProperties("Quiz! Who is the rapper and producer behind 'Gold Digger' featuring Jamie Foxx?", 10, true, true, "Kanye West", "Art/Music"),
            new WildCardProperties("Quiz! Which artist performed the hit song 'Dilemma' with Kelly Rowland?", 10, true, true, "Nelly", "Art/Music"),
            new WildCardProperties("Quiz! Who is the British singer-songwriter behind 'Chasing Pavements' and 'Rolling in the Deep'?", 10, true, true, "Adele", "Art/Music"),
            new WildCardProperties("Quiz! Which artist released the song 'Hey There Delilah' and is part of the band Plain White T's?", 10, true, true, "Tom Higgenson", "Art/Music"),

            // Sport

            new WildCardProperties("Quiz! In which city is the AFL Grand Final traditionally held?", 10, true, true, "Melbourne", "Sport"),
            new WildCardProperties("Quiz! What is the maximum number of players allowed on the field for each team in AFL?", 10, true, true, "18", "Sport"),
            new WildCardProperties("Quiz! Which team has won the most AFL premierships?", 10, true, true, "Essendon", "Sport"),
            new WildCardProperties("Quiz! What is the AFL's highest individual award for players?", 10, true, true, "Brownlow Medal", "Sport"),
            new WildCardProperties("Quiz! Which team is known as the 'Mighty Hawks' in the AFL?", 10, true, true, "Hawthorn", "Sport"),
            new WildCardProperties("Quiz! What is the shape of the ball used in AFL?", 10, true, true, "Oval", "Sport"),
            new WildCardProperties("Quiz! Which team won the 2021 AFL Grand Final?", 10, true, true, "Western Bulldogs", "Sport"),
            new WildCardProperties("Quiz! How many points is a goal worth in AFL?", 10, true, true, "6", "Sport"),
            new WildCardProperties("Quiz! Which team was the first-ever premiership winner of the AFL?", 10, true, true, "Carlton", "Sport"),
            new WildCardProperties("Quiz! In which year was the AFL established?", 10, true, true, "1897", "Sport"),
            new WildCardProperties("Quiz! How many players are on the field for each team in a standard soccer match?", 10, true, true, "11", "Sport"),
            new WildCardProperties("Quiz! Who won the FIFA World Cup in 2018?", 10, true, true, "France", "Sport"),
            new WildCardProperties("Quiz! Which country is known for having the most passionate soccer fans, who are called 'Ultras'?", 10, true, true, "Italy", "Sport"),
            new WildCardProperties("Quiz! Who is the all-time leading goal scorer in men's international soccer?", 10, true, true, "Ali Daei", "Sport"),
            new WildCardProperties("Quiz! Which famous soccer player is known as 'CR7'?", 10, true, true, "Cristiano Ronaldo", "Sport"),
            new WildCardProperties("Quiz! What is the name of the famous soccer tournament between European club teams?", 10, true, true, "UEFA Champions League", "Sport"),
            new WildCardProperties("Quiz! Which country hosted the 2014 FIFA World Cup?", 10, true, true, "Brazil", "Sport"),
            new WildCardProperties("Quiz! Which club has won the most UEFA Champions League titles?", 10, true, true, "Real Madrid", "Sport"),
            new WildCardProperties("Quiz! What is the nickname of the Argentina national soccer team?", 10, true, true, "Albiceleste", "Sport"),
            new WildCardProperties("Quiz! Who won the Ballon d'Or in 2021?", 10, true, true, "Lionel Messi", "Sport"),
            new WildCardProperties("Quiz! How many players are there in a full cricket team?", 10, true, true, "11", "Sport"),
            new WildCardProperties("Quiz! What is the highest individual score by a batsman in a Test cricket match?", 10, true, true, "400 not out", "Sport"),
            new WildCardProperties("Quiz! Which country won the ICC Cricket World Cup in 2019?", 10, true, true, "England", "Sport"),
            new WildCardProperties("Quiz! What is the name of the famous cricket stadium in India known as the 'Eden Gardens'?", 10, true, true, "Kolkata", "Sport"),
            new WildCardProperties("Quiz! How many balls are bowled in one over in cricket?", 10, true, true, "6", "Sport"),
            new WildCardProperties("Quiz! Which country has won the most ICC Cricket World Cup titles?", 10, true, true, "Australia", "Sport"),
            new WildCardProperties("Quiz! What is the name of the traditional rivalry cricket series between England and Australia?", 10, true, true, "The Ashes", "Sport"),
            new WildCardProperties("Quiz! Who is the leading run-scorer in international cricket (combined formats)?", 10, true, true, "Sachin Tendulkar", "Sport"),
            new WildCardProperties("Quiz! In which country did T20 cricket originate?", 10, true, true, "England", "Sport"),
            new WildCardProperties("Quiz! How many players from the fielding team are allowed on the leg side during a delivery in cricket?", 10, true, true, "5", "Sport"),
            new WildCardProperties("Quiz! Which athlete is known as the 'Fastest Man on Earth'?", 10, true, true, "Usain Bolt", "Sport"),
            new WildCardProperties("Quiz! How many players are on a basketball team?", 10, true, true, "5", "Sport"),
            new WildCardProperties("Quiz! In which sport can you perform a 'slam dunk'?", 10, true, true, "Basketball", "Sport"),
            new WildCardProperties("Quiz! What is the name of the annual international tennis tournament held in England?", 10, true, true, "Wimbledon", "Sport"),
            new WildCardProperties("Quiz! Which country won the Rugby World Cup in 2019?", 10, true, true, "South Africa", "Sport"),
            new WildCardProperties("Quiz! What is the highest possible break in snooker?", 10, true, true, "147", "Sport"),
            new WildCardProperties("Quiz! Which country hosted the 2016 Summer Olympics?", 10, true, true, "Brazil", "Sport"),
            new WildCardProperties("Quiz! What is the diameter of a standard basketball hoop?", 10, true, true, "18 inches", "Sport"),
            new WildCardProperties("Quiz! How many players are there on a field hockey team?", 10, true, true, "11", "Sport"),
            new WildCardProperties("Quiz! Which athlete has won the most Olympic gold medals in history?", 10, true, true, "Michael Phelps", "Sport"),
            new WildCardProperties("Quiz! Who is the all-time leading goal scorer in the history of the NBA?", 10, true, true, "Kareem Abdul-Jabbar", "Sport"),
            new WildCardProperties("Quiz! Which country hosted the 2019 ICC Cricket World Cup?", 10, true, true, "England", "Sport"),
            new WildCardProperties("Quiz! How many players are there on a rugby union team?", 10, true, true, "15", "Sport"),
            new WildCardProperties("Quiz! Who won the Formula 1 Drivers' World Championship in 2021?", 10, true, true, "Lewis Hamilton", "Sport"),
            new WildCardProperties("Quiz! In which city is the headquarters of the International Olympic Committee (IOC) located?", 10, true, true, "Lausanne", "Sport"),
            new WildCardProperties("Quiz! Which country has won the most FIFA Women's World Cup titles?", 10, true, true, "United States", "Sport"),
            new WildCardProperties("Quiz! What is the name of the famous horse race that takes place annually in the United Kingdom?", 10, true, true, "The Grand National", "Sport"),
            new WildCardProperties("Quiz! Who is the only tennis player to achieve the Golden Slam (winning all four Grand Slam titles and Olympic gold)?", 10, true, true, "Steffi Graf", "Sport"),
            new WildCardProperties("Quiz! Which team has won the most Super Bowl championships in NFL history?", 10, true, true, "Pittsburgh Steelers", "Sport"),
            new WildCardProperties("Quiz! What sport did Lola Bunny play in Space Jam?", 10, true, true, "Basketball", "Sport")
    };


    public static final WildCardProperties[] EXTRA_WILD_CARDS = {
            new WildCardProperties("Double the current number!", 10, true, false),
            new WildCardProperties("Half the current number!", 10, true, false),
            new WildCardProperties("Reset the number!", 10, true, false),
            new WildCardProperties("Reverse the turn order!", 10, true, false),
            new WildCardProperties("Gain a couple more wildcards to use, I gotchya back!", 10, true, false),
            new WildCardProperties("Lose a couple wildcards :( oh also drink 3 lol!", 10, true, false),
    };

    public static final WildCardProperties[] TASK_WILD_CARDS = {
            new WildCardProperties("Task! Take 1 drink.", 10, true, true),
            new WildCardProperties("Task! Take 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Take 3 drinks.", 10, true, true),
            new WildCardProperties("Task! Finish your drink.", 10, true, true),
            new WildCardProperties("Task! Give 1 drink.", 10, true, true),
            new WildCardProperties("Task! Give 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Give 3 drinks.", 10, true, true),
            new WildCardProperties("Task! Choose a player to finish their drink.", 10, true, true),
            new WildCardProperties("Task! The player to the left takes a drink.", 10, true, true),
            new WildCardProperties("Task! The player to the right takes a drink.", 10, true, true),
            new WildCardProperties("Task! The oldest player takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! The youngest player takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! The player who last peed takes 3 drinks.", 10, true, true),
            new WildCardProperties("Task! The player with the oldest car takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Whoever last rode on a train takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Anyone who is standing takes 4 drinks, why are you standing? Sit down mate.", 10, true, true),
            new WildCardProperties("Task! Anyone who is sitting takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Whoever has the longest hair takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Whoever is wearing a watch takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Whoever has a necklace on takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Double the ending drink (whoever loses must now do double the consequence).", 10, true, true),
            new WildCardProperties("Task! Drink for courage then deliver a line from your favourite film making it as dramatic as possible!", 10, true, true),
            new WildCardProperties("Task! Give 1 drink for every cheese you can name in 10 seconds.", 10, true, true),
            new WildCardProperties("Task! The shortest person at the table must take 4 drinks then give 4 drinks.", 10, true, true),
            new WildCardProperties("Task! Bare your biceps and flex for everyone. The players next to you each drink 2 for the view.", 10, true, true),
            new WildCardProperties("Task! All females drink 3, and all males drink 3. Equality.", 10, true, true),
            new WildCardProperties("Task! Do a handstand and give out 3 drinks.", 10, true, true),
            new WildCardProperties("Task! Choose someone to drink with their non-dominant hand for the next round.", 10, true, true),
            new WildCardProperties("Task! The next person to laugh must take 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Everyone must stand on one leg while drinking.", 10, true, true),
            new WildCardProperties("Task! Recite a tongue twister three times without making a mistake, if you do take 3 drinks.", 10, true, true),
            new WildCardProperties("Task! Drink your whole drink while making eye contact with someone for the entire duration.", 10, true, true),
            new WildCardProperties("Task! The person with the longest fingernails takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! The person with the most expensive item on them takes 3 drinks.", 10, true, true),
            new WildCardProperties("Task! The person with the most keys takes 3 drinks.", 10, true, true),
            new WildCardProperties("Task! The person with the longest beard takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Choose someone to take 2 drinks and perform a breakdance move.", 10, true, true),
            new WildCardProperties("Task! Choose someone to take 2 drinks and recite a poem.", 10, true, true),
            new WildCardProperties("Task! Drink while doing a backbend.", 10, true, true),
            new WildCardProperties("Task! Take a drink while doing a split.", 10, true, true),
            new WildCardProperties("Task! Give a toast to the person who shares your zodiac sign and take a drink.", 10, true, true),
            new WildCardProperties("Task! The person wearing the most buttons on their shirt takes 3 drinks. Mr Fancy aye.", 10, true, true),
            new WildCardProperties("Task! The person with the most watches takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Perform a dramatic reading of a nursery rhyme. Everyone takes a drink.", 10, true, true),
            new WildCardProperties("Task! Impersonate your favorite celebrity. Others guess who it is. If they fail, they drink.", 10, true, true),
            new WildCardProperties("Task! Everyone imitates a farm animal. The last one to start drinks.", 10, true, true),
            new WildCardProperties("Task! Create a new cocktail recipe using three random ingredients. Drink up baby!", 10, true, true),
            new WildCardProperties("Task! Tell a cheesy joke. If others laugh, you're safe. If not, take 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Draw a picture blindfolded. Others rate your masterpiece. If the crowd does not like it, take 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Name three things that should be illegal but aren't. If others agree, you're safe, if not, you take 3 drinks.", 10, true, true),
    };

    public static final WildCardProperties[] TRUTH_WILD_CARDS = {
            new WildCardProperties("Give out a drink if you have ever had a crush on a friend's significant other.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a one-night stand.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever kissed someone of the same gender.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever sent a naughty picture or video to someone.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever used a dating app for casual encounters.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a friends-with-benefits arrangement.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever engaged in a video call of a more... intimate nature.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever flirted with a stranger in a bar or club.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever skinny-dipped in the ocean or a natural body of water.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a romantic dream about someone in this room.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a crush on a celebrity.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever used a dating app while already in a relationship.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a secret admirer.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a steamy hookup in a public place.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a crush on someone in this room.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever kissed someone within minutes of meeting them.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever engaged in role-playing with a partner.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a wardrobe malfunction in public.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a regrettable tattoo.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever tried a dating app while drunk.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a crush on a co-worker.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever lied about your age to someone.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a romantic encounter on a beach.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a crush on a cartoon character.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever made a booty call.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a surprise visit from a lover.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a crush on a friend's sibling.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever flirted with a teacher or boss.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a romantic encounter during a vacation.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever watched adult content in a public place.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a one-night stand while traveling.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a crush on a fictional character.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever lied about your relationship status.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a romantic date on a rooftop.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a crush on a neighbor.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a spontaneous make-out session.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever flirted with someone much older or younger than you.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a romantic encounter in a car.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a crush on a social media influencer.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a steamy chat with a stranger online.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a romantic encounter in a public restroom.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a crush on a friend's ex-partner.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever received a risqué text from the wrong person.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a crush on your boss.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a passionate kiss in the rain.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever fantasized about a co-worker.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a romantic encounter during a festival.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a crush on a teacher.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a provocative photoshoot.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a crush on a best friend's sibling.", 10, true, true),
            new WildCardProperties("Give out a drink if you have ever had a scandalous encounter in an elevator.", 10, true, true),
    };
}
