package com.example.countingdowngame.wildCards.wildCardTypes;

import com.example.countingdowngame.wildCards.WildCardProperties;

public class WildCardData {
    public static final WildCardProperties[] QUIZ_WILD_CARDS = {
            // Science Quiz Questions
            new WildCardProperties("Quiz! What is the deepest ocean on Earth?", 10, true, true, "Pacific Ocean", "Science"),
            new WildCardProperties("Quiz! How many legs does a spider have?", 10, true, true, "8", "Science"),
            new WildCardProperties("Quiz! How many sides does a heptagon have?", 10, true, true, "7", "Science"),
            new WildCardProperties("Quiz! What is the largest planet in our solar system?", 10, true, true, "Jupiter", "Science"),
            new WildCardProperties("Quiz! Can you name all seven colors of the rainbow in order?", 10, true, true, "Red, Orange, Yellow, Green, Blue, Indigo, Violet", "Science"),
            new WildCardProperties("Quiz! What is the formula for calculating the area of a circle?", 10, true, true, "πr^2", "Science"),
            new WildCardProperties("Quiz! What is the boiling point of water in Fahrenheit?", 10, true, true, "212", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for silver on the periodic table?", 10, true, true, "Ag", "Science"),
            new WildCardProperties("Quiz! What is the chemical formula for glucose?", 10, true, true, "C6H12O6", "Science"),
            new WildCardProperties("Quiz! How many chromosomes are in a human body cell?", 10, true, true, "46", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for helium on the periodic table?", 10, true, true, "He", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for oxygen on the periodic table?", 10, true, true, "O", "Science"),
            new WildCardProperties("Quiz! What is the boiling point of water in Celsius?", 10, true, true, "100", "Science"),
            new WildCardProperties("Quiz! Who developed the theory of general relativity?", 10, true, true, "Albert Einstein", "Science"),
            new WildCardProperties("Quiz! What is the atomic number of hydrogen?", 10, true, true, "1", "Science"),
            new WildCardProperties("Quiz! What is the largest organ in the human body?", 10, true, true, "Skin", "Science"),
            new WildCardProperties("Quiz! How many chromosomes are in a human body cell?", 10, true, true, "46", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for helium on the periodic table?", 10, true, true, "He", "Science"),
            new WildCardProperties("Quiz! Who discovered penicillin?", 10, true, true, "Alexander Fleming", "Science"),
            new WildCardProperties("Quiz! What is the formula for calculating the area of a circle?", 10, true, true, "πr^2", "Science"),
            new WildCardProperties("Quiz! What is the largest species of shark?", 10, true, true, "Whale Shark", "Science"),
            new WildCardProperties("Quiz! What is the boiling point of water in Fahrenheit?", 10, true, true, "212", "Science"),
            new WildCardProperties("Quiz! Who is known as the 'father of modern chemistry'?", 10, true, true, "Antoine Lavoisier", "Science"),
            new WildCardProperties("Quiz! What is the formula for calculating density?", 10, true, true, "Density = Mass / Volume", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for iron on the periodic table?", 10, true, true, "Fe", "Science"),
            new WildCardProperties("Quiz! Who proposed the theory of evolution by natural selection?", 10, true, true, "Charles Darwin", "Science"),
            new WildCardProperties("Quiz! What is the largest moon in the solar system?", 10, true, true, "Ganymede", "Science"),
            new WildCardProperties("Quiz! What is the freezing point of water in Celsius?", 10, true, true, "0", "Science"),
            new WildCardProperties("Quiz! Who discovered the law of gravity?", 10, true, true, "Isaac Newton", "Science"),
            new WildCardProperties("Quiz! What is the chemical formula for glucose?", 10, true, true, "C6H12O6", "Science"),
            new WildCardProperties("Quiz! Who invented the first practical telephone?", 10, true, true, "Alexander Graham Bell", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for sodium on the periodic table?", 20, true, true, "Na", "Science"),
            new WildCardProperties("Quiz! What is the process by which plants release water vapor through their leaves?", 20, true, true, "Transpiration", "Science"),
            new WildCardProperties("Quiz! What is the unit of measurement for energy?", 20, true, true, "Joule (J)", "Science"),
            new WildCardProperties("Quiz! What is the hardest substance in the human body?", 20, true, true, "Tooth enamel", "Science"),
            new WildCardProperties("Quiz! What is the chemical formula for sulfuric acid?", 20, true, true, "H2SO4", "Science"),
            new WildCardProperties("Quiz! What is the process of a gas turning into a liquid?", 20, true, true, "Condensation", "Science"),
            new WildCardProperties("Quiz! Which gas makes up about 78% of the Earth's atmosphere?", 20, true, true, "Nitrogen (N2)", "Science"),
            new WildCardProperties("Quiz! What is the unit of measurement for frequency?", 20, true, true, "Hertz (Hz)", "Science"),
            new WildCardProperties("Quiz! What is the process of a solid turning directly into a gas?", 20, true, true, "Sublimation", "Science"),
            new WildCardProperties("Quiz! What is the chemical symbol for copper on the periodic table?", 20, true, true, "Cu", "Science"),
            new WildCardProperties("Quiz! What is the name for the study of fossils?", 20, true, true, "Paleontology", "Science"),
            new WildCardProperties("Quiz! What is the unit of measurement for electric potential difference?", 20, true, true, "Volt (V)", "Science"),
            new WildCardProperties("Quiz! Which gas do humans exhale during respiration?", 20, true, true, "Carbon dioxide (CO2)", "Science"),
            new WildCardProperties("Quiz! What is the process of a liquid turning into a solid?", 20, true, true, "Freezing", "Science"),
            new WildCardProperties("Quiz! What is the chemical formula for methane?", 20, true, true, "CH4", "Science"),
            new WildCardProperties("Quiz! What is the process of energy transfer through electromagnetic waves?", 20, true, true, "Radiation", "Science"),
            new WildCardProperties("Quiz! Which gas is produced during photosynthesis?", 20, true, true, "Oxygen (O2)", "Science"),
            new WildCardProperties("Quiz! What is the unit of measurement for electric resistance?", 20, true, true, "Ohm (Ω)", "Science"),
            new WildCardProperties("Quiz! What is the process of a liquid turning into a gas below its boiling point?", 20, true, true, "Evaporation", "Science"),

// Geography Quiz Questions
            new WildCardProperties("Quiz! What is the national animal of Canada?", 10, true, true, "Beaver", "Geography"),
            new WildCardProperties("Quiz! How many time zones are there in the world?", 10, true, true, "24", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Brazil?", 10, true, true, "Brasília", "Geography"),
            new WildCardProperties("Quiz! Which country is known as the 'Land of the Rising Sun'?", 10, true, true, "Japan", "Geography"),
            new WildCardProperties("Quiz! In which continent is the Sahara Desert located?", 10, true, true, "Africa", "Geography"),
            new WildCardProperties("Quiz! What is the largest country by land area?", 10, true, true, "Russia", "Geography"),
            new WildCardProperties("Quiz! What is the highest mountain in the world?", 10, true, true, "Mount Everest", "Geography"),
            new WildCardProperties("Quiz! What is the largest ocean?", 10, true, true, "Pacific Ocean", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Australia?", 10, true, true, "Canberra", "Geography"),
            new WildCardProperties("Quiz! Which river is the longest in the world?", 10, true, true, "Nile", "Geography"),
            new WildCardProperties("Quiz! What is the official language of Japan?", 10, true, true, "Japanese", "Geography"),
            new WildCardProperties("Quiz! Which city is known as the 'Eternal City'?", 10, true, true, "Rome", "Geography"),
            new WildCardProperties("Quiz! What is the largest desert in the world?", 10, true, true, "Antarctica", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Canada?", 10, true, true, "Ottawa", "Geography"),
            new WildCardProperties("Quiz! Which country is famous for the Great Barrier Reef?", 10, true, true, "Australia", "Geography"),
            new WildCardProperties("Quiz! What is the official language of Brazil?", 10, true, true, "Portuguese", "Geography"),
            new WildCardProperties("Quiz! In which country is the Taj Mahal located?", 10, true, true, "India", "Geography"),
            new WildCardProperties("Quiz! What is the largest lake in Africa?", 10, true, true, "Lake Victoria", "Geography"),
            new WildCardProperties("Quiz! What is the currency of Japan?", 10, true, true, "Japanese yen", "Geography"),
            new WildCardProperties("Quiz! In which country is Mount Kilimanjaro located?", 10, true, true, "Tanzania", "Geography"),
            new WildCardProperties("Quiz! What is the smallest country in the world?", 10, true, true, "Vatican City", "Geography"),
            new WildCardProperties("Quiz! Which country is known for the Pyramids of Giza?", 10, true, true, "Egypt", "Geography"),
            new WildCardProperties("Quiz! Which country is the largest archipelago in the world?", 20, true, true, "Indonesia", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Spain?", 20, true, true, "Madrid", "Geography"),
            new WildCardProperties("Quiz! Which river runs through the Grand Canyon in the United States?", 20, true, true, "Colorado River", "Geography"),
            new WildCardProperties("Quiz! In which continent is the Andes mountain range located?", 20, true, true, "South America", "Geography"),
            new WildCardProperties("Quiz! What is the largest island in the Mediterranean Sea?", 20, true, true, "Sicily", "Geography"),
            new WildCardProperties("Quiz! Which African country is known as the 'Pearl of the Indian Ocean'?", 20, true, true, "Sri Lanka", "Geography"),
            new WildCardProperties("Quiz! What is the official language of Germany?", 20, true, true, "German", "Geography"),
            new WildCardProperties("Quiz! Which country is the world's leading producer of coffee?", 20, true, true, "Brazil", "Geography"),
            new WildCardProperties("Quiz! What is the smallest continent in the world?", 20, true, true, "Australia", "Geography"),
            new WildCardProperties("Quiz! Which river is known as the 'Mother River' in China?", 20, true, true, "Yangtze River", "Geography"),
            new WildCardProperties("Quiz! What is the capital of South Africa?", 20, true, true, "Pretoria", "Geography"),
            new WildCardProperties("Quiz! Which country is the Land of a Thousand Lakes?", 20, true, true, "Finland", "Geography"),
            new WildCardProperties("Quiz! In which U.S. state is the Grand Canyon located?", 20, true, true, "Arizona", "Geography"),
            new WildCardProperties("Quiz! Which country is home to the famous rock formation Uluru (Ayers Rock)?", 20, true, true, "Australia", "Geography"),
            new WildCardProperties("Quiz! What is the largest city in Canada?", 20, true, true, "Toronto", "Geography"),
            new WildCardProperties("Quiz! Which river is the longest in Europe?", 20, true, true, "Volga River", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Argentina?", 20, true, true, "Buenos Aires", "Geography"),
            new WildCardProperties("Quiz! Which country is known as the 'Land of Fire and Ice'?", 20, true, true, "Iceland", "Geography"),
            new WildCardProperties("Quiz! What is the highest waterfall in the world?", 20, true, true, "Angel Falls", "Geography"),
            new WildCardProperties("Quiz! Which city is located on two continents, Europe and Asia?", 20, true, true, "Istanbul", "Geography"),
            new WildCardProperties("Quiz! Which country is known as the 'Land of the Midnight Sun'?", 10, true, true, "Norway", "Geography"),
            new WildCardProperties("Quiz! What is the largest river in the world by discharge volume?", 10, true, true, "Amazon River", "Geography"),
            new WildCardProperties("Quiz! Which country is famous for its tulip fields and windmills?", 10, true, true, "Netherlands", "Geography"),
            new WildCardProperties("Quiz! What is the capital of Russia?", 10, true, true, "Moscow", "Geography"),
            new WildCardProperties("Quiz! Which African country is known as the 'Pearl of Africa'?", 10, true, true, "Uganda", "Geography"),
            new WildCardProperties("Quiz! In which mountain range is Mount Everest located?", 10, true, true, "Himalayas", "Geography"),
            new WildCardProperties("Quiz! What is the largest hot desert in the world?", 10, true, true, "Sahara Desert", "Geography"),
            new WildCardProperties("Quiz! Which country is famous for the Great Wall?", 10, true, true, "China", "Geography"),


// History Quiz Questions
            new WildCardProperties("Quiz! Who is the current Prime Minister of Japan?", 10, true, true, "Yoshihide Suga", "History"),
            new WildCardProperties("Quiz! In which year did World War I begin?", 10, true, true, "1914", "History"),
            new WildCardProperties("Quiz! Who was the first President of the United States?", 10, true, true, "George Washington", "History"),
            new WildCardProperties("Quiz! In which year did the United States declare independence from Great Britain?", 10, true, true, "1776", "History"),
            new WildCardProperties("Quiz! Who was the leader of the Soviet Union during World War II?", 10, true, true, "Joseph Stalin", "History"),
            new WildCardProperties("Quiz! Who painted the Mona Lisa?", 10, true, true, "Leonardo da Vinci", "History"),
            new WildCardProperties("Quiz! In which year did the Titanic sink?", 10, true, true, "1912", "History"),
            new WildCardProperties("Quiz! Who wrote the play 'Romeo and Juliet'?", 10, true, true, "William Shakespeare", "History"),
            new WildCardProperties("Quiz! In which year did the American Civil War end?", 10, true, true, "1865", "History"),
            new WildCardProperties("Quiz! Who was the first female Prime Minister of the United Kingdom?", 10, true, true, "Margaret Thatcher", "History"),
            new WildCardProperties("Quiz! In which country was Adolf Hitler born?", 10, true, true, "Austria", "History"),
            new WildCardProperties("Quiz! What is the significance of the Magna Carta?", 10, true, true, "It established the principle of the rule of law", "History"),
            new WildCardProperties("Quiz! Who was the last pharaoh of ancient Egypt?", 10, true, true, "Cleopatra", "History"),
            new WildCardProperties("Quiz! In which year did the Berlin Wall fall?", 10, true, true, "1989", "History"),
            new WildCardProperties("Quiz! Who was the first man to walk on the moon?", 10, true, true, "Neil Armstrong", "History"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Starry Night'?", 10, true, true, "Vincent van Gogh", "History"),
            new WildCardProperties("Quiz! In which year did World War II end?", 10, true, true, "1945", "History"),
            new WildCardProperties("Quiz! Who wrote the novel 'Pride and Prejudice'?", 10, true, true, "Jane Austen", "History"),
            new WildCardProperties("Quiz! What is the significance of the Declaration of Independence?", 10, true, true, "It announced the United States' independence from Great Britain", "History"),
            new WildCardProperties("Quiz! Who was the first Emperor of Rome?", 10, true, true, "Augustus", "History"),
            new WildCardProperties("Quiz! In which year did the Renaissance begin?", 10, true, true, "14th century", "History"),
            new WildCardProperties("Quiz! Who was the founder of the Mongol Empire?", 20, true, true, "Genghis Khan", "History"),
            new WildCardProperties("Quiz! In which year did the French Revolution begin?", 20, true, true, "1789", "History"),
            new WildCardProperties("Quiz! Who was the first female pharaoh of ancient Egypt?", 20, true, true, "Hatshepsut", "History"),
            new WildCardProperties("Quiz! In which year did the Industrial Revolution start?", 20, true, true, "1760", "History"),
            new WildCardProperties("Quiz! Who was the first woman to fly solo across the Atlantic?", 20, true, true, "Amelia Earhart", "History"),
            new WildCardProperties("Quiz! In which year did the Cuban Missile Crisis occur?", 20, true, true, "1962", "History"),
            new WildCardProperties("Quiz! Who was the first African American President of the United States?", 20, true, true, "Barack Obama", "History"),
            new WildCardProperties("Quiz! In which year did the Battle of Gettysburg take place during the American Civil War?", 20, true, true, "1863", "History"),
            new WildCardProperties("Quiz! Who was the first woman to win a Nobel Prize?", 20, true, true, "Marie Curie", "History"),
            new WildCardProperties("Quiz! In which year did the Russian Revolution occur?", 20, true, true, "1917", "History"),
            new WildCardProperties("Quiz! Who was the first European explorer to reach India by sea?", 20, true, true, "Vasco da Gama", "History"),
            new WildCardProperties("Quiz! In which year did the American Revolution end?", 20, true, true, "1783", "History"),
            new WildCardProperties("Quiz! Who was the Roman general who led the conquest of Gaul?", 20, true, true, "Julius Caesar", "History"),
            new WildCardProperties("Quiz! In which year did the Treaty of Versailles end World War I?", 20, true, true, "1919", "History"),
            new WildCardProperties("Quiz! Who was the legendary king of Uruk in ancient Mesopotamia?", 20, true, true, "Gilgamesh", "History"),
            new WildCardProperties("Quiz! In which year did the American colonies declare independence from Spain?", 20, true, true, "1810", "History"),
            new WildCardProperties("Quiz! Who was the first Roman Emperor?", 20, true, true, "Augustus", "History"),
            new WildCardProperties("Quiz! In which year did the Treaty of Paris end the American Revolutionary War?", 20, true, true, "1783", "History"),
            new WildCardProperties("Quiz! Who was the leader of the Bolshevik Party during the October Revolution?", 20, true, true, "Vladimir Lenin", "History"),
            new WildCardProperties("Quiz! In which year did the Black Death (Bubonic Plague) spread across Europe?", 20, true, true, "1347", "History"),
            new WildCardProperties("Quiz! Who was the first female astronaut to travel to space?", 10, true, true, "Valentina Tereshkova", "History"),
            new WildCardProperties("Quiz! In which year did the Spanish conquistador Hernán Cortés conquer the Aztec Empire?", 10, true, true, "1521", "History"),
            new WildCardProperties("Quiz! Who was the ancient Egyptian queen who ruled alongside her husband, Pharaoh Akhenaten?", 10, true, true, "Nefertiti", "History"),
            new WildCardProperties("Quiz! In which year did the Battle of Waterloo take place, leading to the defeat of Napoleon Bonaparte?", 10, true, true, "1815", "History"),
            new WildCardProperties("Quiz! Who was the first President of the United States to be impeached?", 10, true, true, "Andrew Johnson", "History"),
            new WildCardProperties("Quiz! In which year did the Great Fire of London devastate the city?", 10, true, true, "1666", "History"),
            new WildCardProperties("Quiz! Who was the Mongol emperor who established the Yuan Dynasty in China?", 10, true, true, "Kublai Khan", "History"),
            new WildCardProperties("Quiz! In which year did the Suez Canal open, connecting the Mediterranean Sea to the Red Sea?", 10, true, true, "1869", "History"),
            new WildCardProperties("Quiz! Who was the leader of the Allied forces during World War II?", 10, true, true, "Dwight D. Eisenhower", "History"),


// Art/Music Quiz Questions
            new WildCardProperties("Quiz! How many symphonies did Ludwig van Beethoven compose?", 10, true, true, "9", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Mona Lisa'?", 10, true, true, "Leonardo da Vinci", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous symphony 'Symphony No. 9'?", 10, true, true, "Ludwig van Beethoven", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Starry Night'?", 10, true, true, "Vincent van Gogh", "Art/Music"),
            new WildCardProperties("Quiz! Who wrote the play 'Hamlet'?", 10, true, true, "William Shakespeare", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous piano composition 'Für Elise'?", 10, true, true, "Ludwig van Beethoven", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the novel 'The Picture of Dorian Gray'?", 10, true, true, "Oscar Wilde", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Last Supper'?", 10, true, true, "Leonardo da Vinci", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous ballet 'Swan Lake'?", 10, true, true, "Pyotr Ilyich Tchaikovsky", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead guitarist of the band Led Zeppelin?", 10, true, true, "Jimmy Page", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Scream'?", 10, true, true, "Edvard Munch", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous opera 'The Magic Flute'?", 10, true, true, "Wolfgang Amadeus Mozart", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the novel 'War and Peace'?", 10, true, true, "Leo Tolstoy", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'Guernica'?", 10, true, true, "Pablo Picasso", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous symphony 'Symphony No. 5'?", 10, true, true, "Ludwig van Beethoven", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead singer of the band The Rolling Stones?", 10, true, true, "Mick Jagger", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Birth of Venus'?", 10, true, true, "Sandro Botticelli", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous piano composition 'Clair de Lune'?", 10, true, true, "Claude Debussy", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the novel 'The Great Gatsby'?", 10, true, true, "F. Scott Fitzgerald", "Art/Music"),
            new WildCardProperties("Quiz! How many players are there on a soccer team?", 10, true, true, "11", "Art/Music"),
            new WildCardProperties("Quiz! Who is the Greek god of the sea?", 10, true, true, "Poseidon", "Art/Music"),
            new WildCardProperties("Quiz! How many strings does a standard violin have?", 10, true, true, "4", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead vocalist of the band Queen?", 20, true, true, "Freddie Mercury", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous opera 'Carmen'?", 20, true, true, "Georges Bizet", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead guitarist of the band Guns N' Roses?", 20, true, true, "Slash", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'Girl with a Pearl Earring'?", 20, true, true, "Johannes Vermeer", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous piano composition 'Moonlight Sonata'?", 20, true, true, "Ludwig van Beethoven", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the play 'Romeo and Juliet'?", 20, true, true, "William Shakespeare", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Creation of Adam'?", 20, true, true, "Michelangelo", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous ballet 'The Nutcracker'?", 20, true, true, "Pyotr Ilyich Tchaikovsky", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the novel 'The Da Vinci Code'?", 20, true, true, "Dan Brown", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'Water Lilies'?", 20, true, true, "Claude Monet", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous opera 'La Traviata'?", 20, true, true, "Giuseppe Verdi", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead singer of the band Aerosmith?", 20, true, true, "Steven Tyler", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Guernica'?", 20, true, true, "Pablo Picasso", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous piano composition 'Nocturne in E-flat Major'?", 20, true, true, "Frederic Chopin", "Art/Music"),
            new WildCardProperties("Quiz! Who is the author of the novel 'The Lord of the Rings'?", 20, true, true, "J.R.R. Tolkien", "Art/Music"),
            new WildCardProperties("Quiz! Who composed the famous opera 'The Marriage of Figaro'?", 20, true, true, "Wolfgang Amadeus Mozart", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead guitarist of the band AC/DC?", 20, true, true, "Angus Young", "Art/Music"),
            new WildCardProperties("Quiz! Who painted the famous artwork 'The Persistence of Memory'?", 20, true, true, "Salvador Dalí", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead singer of the band Coldplay?", 10, true, true, "Chris Martin", "Art/Music"),
            new WildCardProperties("Quiz! Which artist sang the song 'Crazy' and collaborated with Gnarls Barkley?", 10, true, true, "CeeLo Green", "Art/Music"),
            new WildCardProperties("Quiz! Who is the singer behind the hit 'Yeah!' featuring Lil Jon and Ludacris?", 10, true, true, "Usher", "Art/Music"),
            new WildCardProperties("Quiz! Which artist performed 'I Want It That Way' with the Backstreet Boys?", 10, true, true, "AJ McLean", "Art/Music"),
            new WildCardProperties("Quiz! Who is the lead vocalist of the band Coldplay, known for songs like 'Yellow' and 'Fix You'?", 10, true, true, "Chris Martin", "Art/Music"),
            new WildCardProperties("Quiz! Which artist released the song 'Poker Face' and is known for her unique fashion style?", 10, true, true, "Lady Gaga", "Art/Music"),
            new WildCardProperties("Quiz! Who is the rapper and producer behind 'Gold Digger' featuring Jamie Foxx?", 10, true, true, "Kanye West", "Art/Music"),
            new WildCardProperties("Quiz! Which artist performed the hit song 'Dilemma' with Kelly Rowland?", 10, true, true, "Nelly", "Art/Music"),
            new WildCardProperties("Quiz! Who is the British singer-songwriter behind 'Chasing Pavements' and 'Rolling in the Deep'?", 10, true, true, "Adele", "Art/Music"),
            new WildCardProperties("Quiz! Which artist released the song 'Hey There Delilah' and is part of the band Plain White T's?", 10, true, true, "Tom Higgenson", "Art/Music"),

            // Sport

            new WildCardProperties("Quiz! In which city is the AFL Grand Final traditionally held?", 10, true, true, "Melbourne", "Sport"),
            new WildCardProperties("Quiz! What is the maximum number of players allowed on the field for each team in AFL?", 10, true, true, "18", "Sport"),
            new WildCardProperties("Quiz! Which team has won the most AFL premierships?", 10, true, true, "Essendon", "Sport"),
            new WildCardProperties("Quiz! What is the AFL's highest individual award for players?", 10, true, true, "Brownlow Medal", "Sport"),
            new WildCardProperties("Quiz! Which team is known as the 'Mighty Hawks' in the AFL?", 10, true, true, "Hawthorn", "Sport"),
            new WildCardProperties("Quiz! What is the shape of the ball used in AFL?", 10, true, true, "Oval", "Sport"),
            new WildCardProperties("Quiz! Which team won the 2021 AFL Grand Final?", 10, true, true, "Western Bulldogs", "Sport"),
            new WildCardProperties("Quiz! How many points is a goal worth in AFL?", 10, true, true, "6", "Sport"),
            new WildCardProperties("Quiz! Which team was the first-ever premiership winner of the AFL?", 10, true, true, "Carlton", "Sport"),
            new WildCardProperties("Quiz! In which year was the AFL established?", 10, true, true, "1897", "Sport"),
            new WildCardProperties("Quiz! How many players are on the field for each team in a standard soccer match?", 10, true, true, "11", "Sport"),
            new WildCardProperties("Quiz! Who won the FIFA World Cup in 2018?", 10, true, true, "France", "Sport"),
            new WildCardProperties("Quiz! Which country is known for having the most passionate soccer fans, who are called 'Ultras'?", 10, true, true, "Italy", "Sport"),
            new WildCardProperties("Quiz! Who is the all-time leading goal scorer in men's international soccer?", 10, true, true, "Ali Daei", "Sport"),
            new WildCardProperties("Quiz! Which famous soccer player is known as 'CR7'?", 10, true, true, "Cristiano Ronaldo", "Sport"),
            new WildCardProperties("Quiz! What is the name of the famous soccer tournament between European club teams?", 10, true, true, "UEFA Champions League", "Sport"),
            new WildCardProperties("Quiz! Which country hosted the 2014 FIFA World Cup?", 10, true, true, "Brazil", "Sport"),
            new WildCardProperties("Quiz! Which club has won the most UEFA Champions League titles?", 10, true, true, "Real Madrid", "Sport"),
            new WildCardProperties("Quiz! What is the nickname of the Argentina national soccer team?", 10, true, true, "Albiceleste", "Sport"),
            new WildCardProperties("Quiz! Who won the Ballon d'Or in 2021?", 10, true, true, "Lionel Messi", "Sport"),
            new WildCardProperties("Quiz! How many players are there in a full cricket team?", 10, true, true, "11", "Sport"),
            new WildCardProperties("Quiz! What is the highest individual score by a batsman in a Test cricket match?", 10, true, true, "400 not out", "Sport"),
            new WildCardProperties("Quiz! Which country won the ICC Cricket World Cup in 2019?", 10, true, true, "England", "Sport"),
            new WildCardProperties("Quiz! What is the name of the famous cricket stadium in India known as the 'Eden Gardens'?", 10, true, true, "Kolkata", "Sport"),
            new WildCardProperties("Quiz! How many balls are bowled in one over in cricket?", 10, true, true, "6", "Sport"),
            new WildCardProperties("Quiz! Which country has won the most ICC Cricket World Cup titles?", 10, true, true, "Australia", "Sport"),
            new WildCardProperties("Quiz! What is the name of the traditional rivalry cricket series between England and Australia?", 10, true, true, "The Ashes", "Sport"),
            new WildCardProperties("Quiz! Who is the leading run-scorer in international cricket (combined formats)?", 10, true, true, "Sachin Tendulkar", "Sport"),
            new WildCardProperties("Quiz! In which country did T20 cricket originate?", 10, true, true, "England", "Sport"),
            new WildCardProperties("Quiz! How many players from the fielding team are allowed on the leg side during a delivery in cricket?", 10, true, true, "5", "Sport"),
            new WildCardProperties("Quiz! Which athlete is known as the 'Fastest Man on Earth'?", 10, true, true, "Usain Bolt", "Sport"),
            new WildCardProperties("Quiz! How many players are on a basketball team?", 10, true, true, "5", "Sport"),
            new WildCardProperties("Quiz! In which sport can you perform a 'slam dunk'?", 10, true, true, "Basketball", "Sport"),
            new WildCardProperties("Quiz! What is the name of the annual international tennis tournament held in England?", 10, true, true, "Wimbledon", "Sport"),
            new WildCardProperties("Quiz! Which country won the Rugby World Cup in 2019?", 10, true, true, "South Africa", "Sport"),
            new WildCardProperties("Quiz! What is the highest possible break in snooker?", 10, true, true, "147", "Sport"),
            new WildCardProperties("Quiz! Which country hosted the 2016 Summer Olympics?", 10, true, true, "Brazil", "Sport"),
            new WildCardProperties("Quiz! What is the diameter of a standard basketball hoop?", 10, true, true, "18 inches", "Sport"),
            new WildCardProperties("Quiz! How many players are there on a field hockey team?", 10, true, true, "11", "Sport"),
            new WildCardProperties("Quiz! Which athlete has won the most Olympic gold medals in history?", 10, true, true, "Michael Phelps", "Sport"),
            new WildCardProperties("Quiz! Who is the all-time leading goal scorer in the history of the NBA?", 10, true, true, "Kareem Abdul-Jabbar", "Sport"),
            new WildCardProperties("Quiz! Which country hosted the 2019 ICC Cricket World Cup?", 10, true, true, "England", "Sport"),
            new WildCardProperties("Quiz! How many players are there on a rugby union team?", 10, true, true, "15", "Sport"),
            new WildCardProperties("Quiz! Who won the Formula 1 Drivers' World Championship in 2021?", 10, true, true, "Lewis Hamilton", "Sport"),
            new WildCardProperties("Quiz! In which city is the headquarters of the International Olympic Committee (IOC) located?", 10, true, true, "Lausanne", "Sport"),
            new WildCardProperties("Quiz! Which country has won the most FIFA Women's World Cup titles?", 10, true, true, "United States", "Sport"),
            new WildCardProperties("Quiz! What is the name of the famous horse race that takes place annually in the United Kingdom?", 10, true, true, "The Grand National", "Sport"),
            new WildCardProperties("Quiz! Who is the only tennis player to achieve the Golden Slam (winning all four Grand Slam titles and Olympic gold)?", 10, true, true, "Steffi Graf", "Sport"),
            new WildCardProperties("Quiz! Which team has won the most Super Bowl championships in NFL history?", 10, true, true, "Pittsburgh Steelers", "Sport"),
            new WildCardProperties("Quiz! What sport did Lola Bunny play in Space Jam?", 10, true, true, "Basketball", "Sport"),

            // Movies

            new WildCardProperties("Quiz! Which 1994 movie features a mysterious briefcase that emits a golden light?", 20, true, true, "Pulp Fiction", "Movies"),
            new WildCardProperties("Quiz! In the movie 'Blade Runner', what is the term used for humanoid robots?", 20, true, true, "Replicants", "Movies"),
            new WildCardProperties("Quiz! Which 1982 science fiction film involves a young boy who befriends an alien stranded on Earth?", 20, true, true, "E.T. the Extra-Terrestrial", "Movies"),
            new WildCardProperties("Quiz! What is the name of the virtual reality world in the movie 'Ready Player One'?", 20, true, true, "OASIS", "Movies"),
            new WildCardProperties("Quiz! Which movie features a former assassin seeking revenge for the death of his dog?", 20, true, true, "John Wick", "Movies"),
            new WildCardProperties("Quiz! In 'The Silence of the Lambs', what is the nickname of the serial killer being pursued?", 20, true, true, "Buffalo Bill", "Movies"),
            new WildCardProperties("Quiz! Which movie follows the story of a jazz musician and an aspiring actress in Los Angeles?", 20, true, true, "La La Land", "Movies"),
            new WildCardProperties("Quiz! Who directed the movie 'Fight Club'?", 20, true, true, "David Fincher", "Movies"),
            new WildCardProperties("Quiz! In the film 'Inglourious Basterds', what is the nickname of the Nazi officer who becomes the target of the Basterds?", 20, true, true, "The Jew Hunter", "Movies"),
            new WildCardProperties("Quiz! Which movie features a mentally challenged man with an IQ of 75?", 20, true, true, "Forrest Gump", "Movies"),
            new WildCardProperties("Quiz! Who played the character of Lisbeth Salander in the movie 'The Girl with the Dragon Tattoo' (2011)?", 20, true, true, "Rooney Mara", "Movies"),
            new WildCardProperties("Quiz! What is the name of the mysterious island theme park in 'Jurassic Park'?", 20, true, true, "Isla Nublar", "Movies"),
            new WildCardProperties("Quiz! Which movie is about a magician duo battling each other in the late 1800s?", 20, true, true, "The Prestige", "Movies"),
            new WildCardProperties("Quiz! Who portrayed the character of Anton Chigurh in the movie 'No Country for Old Men'?", 20, true, true, "Javier Bardem", "Movies"),
            new WildCardProperties("Quiz! Which movie involves a group of astronauts trying to survive on a desolate planet after a dust storm?", 20, true, true, "The Martian", "Movies"),
            new WildCardProperties("Quiz! In the film 'Oldboy', what is the main character's quest for vengeance fueled by?", 20, true, true, "Revenge for his daughter", "Movies"),
            new WildCardProperties("Quiz! Which movie is based on the true story of a man who spends years searching for the meaning of a cryptic message?", 20, true, true, "The Da Vinci Code", "Movies"),
            new WildCardProperties("Quiz! Who directed the movie 'Interstellar'?", 20, true, true, "Christopher Nolan", "Movies"),
            new WildCardProperties("Quiz! In the film 'Donnie Darko', what is the name of Donnie's imaginary friend?", 20, true, true, "Frank", "Movies"),
            new WildCardProperties("Quiz! Which movie features a group of magicians known as 'The Four Horsemen' performing heists during their shows?", 20, true, true, "Now You See Me", "Movies"),
            new WildCardProperties("Quiz! Who played the role of Clarice Starling in the movie 'The Silence of the Lambs'?", 20, true, true, "Jodie Foster", "Movies"),
            new WildCardProperties("Quiz! What is the name of the AI system that runs the spaceship in '2001: A Space Odyssey'?", 20, true, true, "HAL 9000", "Movies"),
            new WildCardProperties("Quiz! Which movie is about a man who experiences time backward from the moment of his death?", 20, true, true, "The Curious Case of Benjamin Button", "Movies"),
            new WildCardProperties("Quiz! In 'The Matrix', what is the name of the virtual reality world where most humans live?", 20, true, true, "The Matrix", "Movies"),
            new WildCardProperties("Quiz! What is the name of the fictional African kingdom in 'Black Panther'?", 20, true, true, "Wakanda", "Movies"),
            new WildCardProperties("Quiz! Which movie tells the story of a mute woman who falls in love with an amphibious creature?", 20, true, true, "The Shape of Water", "Movies"),
            new WildCardProperties("Quiz! Who directed the movie 'Taxi Driver'?", 20, true, true, "Martin Scorsese", "Movies"),
            new WildCardProperties("Quiz! In 'The Departed', what is the alias of the undercover cop played by Leonardo DiCaprio?", 20, true, true, "Billy Costigan", "Movies"),
            new WildCardProperties("Quiz! Which movie is about a chess prodigy who becomes a grandmaster and battles addiction?", 20, true, true, "Searching for Bobby Fischer", "Movies"),
            new WildCardProperties("Quiz! What is the name of the ship in the 'Alien' movie franchise?", 20, true, true, "Nostromo", "Movies"),
            new WildCardProperties("Quiz! Which movie involves a high school teacher who starts cooking meth to secure his family's financial future?", 20, true, true, "Breaking Bad", "Movies"),
            new WildCardProperties("Quiz! Who played the role of Patrick Bateman in the movie 'American Psycho'?", 20, true, true, "Christian Bale", "Movies"),
            new WildCardProperties("Quiz! What is the name of the group of rebels fighting against the Empire in 'Star Wars'?", 20, true, true, "The Rebel Alliance", "Movies"),
            new WildCardProperties("Quiz! Which movie is based on the true story of a man who survived on a deserted island for four years?", 20, true, true, "Cast Away", "Movies"),
            new WildCardProperties("Quiz! Who directed the movie 'A Clockwork Orange'?", 20, true, true, "Stanley Kubrick", "Movies"),
            new WildCardProperties("Quiz! In the film 'Se7en', what is the serial killer's motive for his gruesome murders?", 20, true, true, "The Seven Deadly Sins", "Movies"),
            new WildCardProperties("Quiz! Which movie features a hacker known as 'Neo' who discovers the truth about reality?", 20, true, true, "The Matrix", "Movies"),
            new WildCardProperties("Quiz! What is the name of the fictional African city in 'Black Panther'?", 20, true, true, "Wakanda", "Movies"),
            new WildCardProperties("Quiz! Which movie is about a woman who hires a hitman to kill her abusive husband?", 20, true, true, "Fargo", "Movies"),
            new WildCardProperties("Quiz! Who played the character of 'Keyser Söze' in the movie 'The Usual Suspects'?", 20, true, true, "Kevin Spacey", "Movies"),
            new WildCardProperties("Quiz! What is the name of the computer program that creates the virtual reality world in 'The Matrix'?", 20, true, true, "The Architect", "Movies"),
            new WildCardProperties("Quiz! Which movie follows the life of a jazz musician trying to achieve his dreams in Los Angeles?", 20, true, true, "Whiplash", "Movies"),
            new WildCardProperties("Quiz! In the film 'Drive', what is the name of the mysterious and silent stuntman and getaway driver?", 20, true, true, "Driver", "Movies"),
            new WildCardProperties("Quiz! Which movie is about a girl who is the lone survivor of a massacre carried out by her demented uncle?", 20, true, true, "Texas Chainsaw Massacre", "Movies"),
            new WildCardProperties("Quiz! Who directed the movie 'Apocalypse Now'?", 20, true, true, "Francis Ford Coppola", "Movies"),
            new WildCardProperties("Quiz! In 'The Shining', what phrase does Jack Nicholson's character repeatedly type on his typewriter?", 20, true, true, "All work and no play makes Jack a dull boy", "Movies"),
            new WildCardProperties("Quiz! Which 2014 movie tells the story of a man with dissociative identity disorder?", 20, true, true, "Split", "Movies"),
            new WildCardProperties("Quiz! Who played the character of Don Vito Corleone in the movie 'The Godfather'?", 20, true, true, "Marlon Brando", "Movies"),
            new WildCardProperties("Quiz! Which movie is about a man who becomes trapped in a time loop, reliving the same day repeatedly?", 20, true, true, "Groundhog Day", "Movies"),
            new WildCardProperties("Quiz! Who directed the science fiction film 'The Fifth Element'?", 20, true, true, "Luc Besson", "Movies"),

            //Video Games

            new WildCardProperties("Quiz! In the game 'The Witcher 3: Wild Hunt', what is the name of Geralt's adopted daughter?", 20, true, true, "Ciri", "Video Games"),
            new WildCardProperties("Quiz! Which critically acclaimed video game has a protagonist named Arthur Morgan?", 20, true, true, "Red Dead Redemption 2", "Video Games"),
            new WildCardProperties("Quiz! In the 'Dark Souls' series, what is the name of the enigmatic figure who guides the player?", 20, true, true, "The Fire Keeper", "Video Games"),
            new WildCardProperties("Quiz! Which video game is set in the dystopian city of Dunwall and features a supernatural assassin?", 20, true, true, "Dishonored", "Video Games"),
            new WildCardProperties("Quiz! In 'The Legend of Zelda: Ocarina of Time', what is the name of the final boss?", 20, true, true, "Ganondorf", "Video Games"),
            new WildCardProperties("Quiz! Which video game series features the character Solid Snake?", 20, true, true, "Metal Gear Solid", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the protagonist in the video game 'Celeste'?", 20, true, true, "Madeline", "Video Games"),
            new WildCardProperties("Quiz! In the 'Dark Souls' series, what is the term used for regaining lost experience points upon death?", 20, true, true, "Bloodstain Retrieval", "Video Games"),
            new WildCardProperties("Quiz! Which video game series is set in the fictional city of Rapture?", 20, true, true, "BioShock", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the cyberpunk-themed video game released by CD Projekt Red in 2020?", 20, true, true, "Cyberpunk 2077", "Video Games"),
            new WildCardProperties("Quiz! In 'The Elder Scrolls V: Skyrim', what is the name of the dragon that players can summon?", 20, true, true, "Odahviing", "Video Games"),
            new WildCardProperties("Quiz! Which video game features a character named Aloy who hunts robotic creatures?", 20, true, true, "Horizon Zero Dawn", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the criminal organization in the video game 'Grand Theft Auto V'?", 20, true, true, "The Merryweather Security Consulting", "Video Games"),
            new WildCardProperties("Quiz! In the 'Dark Souls' series, what is the term used for defeating a boss without taking damage?", 20, true, true, "No-Hit Run", "Video Games"),
            new WildCardProperties("Quiz! Which video game franchise involves a protagonist named Samus Aran, who battles space pirates and aliens?", 20, true, true, "Metroid", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the kingdom that Princess Peach rules in the 'Super Mario' series?", 20, true, true, "Mushroom Kingdom", "Video Games"),
            new WildCardProperties("Quiz! In the game 'Hollow Knight', what is the name of the protagonist?", 20, true, true, "The Knight", "Video Games"),
            new WildCardProperties("Quiz! Which video game series involves a conflict between the Helghast and the Interplanetary Strategic Alliance?", 20, true, true, "Killzone", "Video Games"),
            new WildCardProperties("Quiz! What is the objective of the game 'Hades'?", 20, true, true, "To escape from the Underworld", "Video Games"),
            new WildCardProperties("Quiz! In the 'Resident Evil' series, what is the name of the pharmaceutical company responsible for the outbreak?", 20, true, true, "Umbrella Corporation", "Video Games"),
            new WildCardProperties("Quiz! Which video game features a protagonist named Commander Shepard?", 20, true, true, "Mass Effect", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the mysterious entity that grants the protagonist powers in 'Control'?", 20, true, true, "The Board", "Video Games"),
            new WildCardProperties("Quiz! Which video game series involves a protagonist named Nathan Drake?", 20, true, true, "Uncharted", "Video Games"),
            new WildCardProperties("Quiz! In the game 'Sekiro: Shadows Die Twice', what is the name of the one-armed shinobi?", 20, true, true, "Wolf", "Video Games"),
            new WildCardProperties("Quiz! Which video game features a conflict between the Helghast and the Interplanetary Strategic Alliance?", 20, true, true, "Killzone", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the main character in the 'Dead Space' video game series?", 20, true, true, "Isaac Clarke", "Video Games"),
            new WildCardProperties("Quiz! In the game 'Dark Souls III', what is the name of the firekeeper at Firelink Shrine?", 20, true, true, "Anastacia of Astora", "Video Games"),
            new WildCardProperties("Quiz! Which video game involves controlling a character named Chell, who navigates through test chambers?", 20, true, true, "Portal", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the artificial intelligence in 'Halo'?", 20, true, true, "Cortana", "Video Games"),
            new WildCardProperties("Quiz! In the 'NieR' series, what is the name of the protagonist who seeks to save his daughter?", 20, true, true, "Nier", "Video Games"),
            new WildCardProperties("Quiz! Which video game franchise is set in the post-apocalyptic world of Sera?", 20, true, true, "Gears of War", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the protagonist in the 'Hitman' video game series?", 20, true, true, "Agent 47", "Video Games"),
            new WildCardProperties("Quiz! In 'Celeste', what is the name of the mountain the protagonist climbs?", 20, true, true, "Mount Celeste", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the protagonist in the game 'Hollow Knight'?", 20, true, true, "The Knight", "Video Games"),
            new WildCardProperties("Quiz! In 'Metal Gear Solid 3: Snake Eater', what is the name of the main antagonist?", 20, true, true, "Volgin", "Video Games"),
            new WildCardProperties("Quiz! Which video game features a character named Kratos, who seeks revenge against the gods?", 20, true, true, "God of War", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the protagonist in the video game 'Bloodborne'?", 20, true, true, "The Hunter", "Video Games"),
            new WildCardProperties("Quiz! In the game 'Control', what is the name of the government agency investigating paranatural phenomena?", 20, true, true, "Federal Bureau of Control", "Video Games"),
            new WildCardProperties("Quiz! In the video game 'Nier: Automata', what is the name of the android protagonist battling against the machines?", 20, true, true, "2B", "Video Games"),
            new WildCardProperties("Quiz! Which video game series features a group of elite soldiers known as the Ghosts, who carry out special operations missions?", 20, true, true, "Tom Clancy's Ghost Recon", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the sentient AI construct in the 'Halo' series that serves as the main antagonist?", 20, true, true, "The Didact", "Video Games"),
            new WildCardProperties("Quiz! In 'The Legend of Zelda: Breath of the Wild', what is the name of the kingdom that was destroyed 100 years before the events of the game?", 20, true, true, "Hyrule", "Video Games"),
            new WildCardProperties("Quiz! Which video game series follows the adventures of a young man named Link, who must rescue Princess Zelda from the evil villain Ganon?", 20, true, true, "The Legend of Zelda", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the main antagonist in the 'Assassin's Creed' series, an ancient organization seeking control over humanity?", 20, true, true, "The Templars (Order of the Knights Templar)", "Video Games"),
            new WildCardProperties("Quiz! In the game 'Final Fantasy VII', what is the name of the villain who seeks to destroy the planet by summoning a meteor?", 20, true, true, "Sephiroth", "Video Games"),
            new WildCardProperties("Quiz! Which video game series features a protagonist named Ezio Auditore da Firenze, who seeks revenge against the Templar Order?", 20, true, true, "Assassin's Creed II", "Video Games"),
            new WildCardProperties("Quiz! What is the name of the AI companion that assists the player in 'Half-Life 2' and becomes a key character in the series?", 20, true, true, "Alyx Vance", "Video Games"),
            new WildCardProperties("Quiz! In the game 'The Last of Us', what is the name of the fungal infection that has devastated the world and turned humans into hostile creatures?", 20, true, true, "Cordyceps Brain Infection (CBI)", "Video Games"),
            new WildCardProperties("Quiz! Which video game series involves a fictional war between the Helghan Empire and the Interplanetary Strategic Alliance?", 20, true, true, "Killzone", "Video Games")


    };


    public static final WildCardProperties[] EXTRA_WILD_CARDS = {
            new WildCardProperties("Double the current number!", 10, true, false),
            new WildCardProperties("Half the current number!", 10, true, false),
            new WildCardProperties("Reset the number!", 10, true, false),
            new WildCardProperties("Reverse the turn order!", 10, true, false),
            new WildCardProperties("Gain a couple more wildcards to use, I gotchya back!", 10, true, false),
            new WildCardProperties("Lose a couple wildcards\n\n:( oh also drink 3 lol!", 10, true, false),
    };

    public static final WildCardProperties[] TASK_WILD_CARDS = {
            new WildCardProperties("Task! Take 1 drink.", 10, true, true),
            new WildCardProperties("Task! Take 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Take 3 drinks.", 10, true, true),
            new WildCardProperties("Task! Finish your drink.", 10, true, true),
            new WildCardProperties("Task! Give 1 drink.", 10, true, true),
            new WildCardProperties("Task! Give 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Give 3 drinks.", 10, true, true),
            new WildCardProperties("Task! Choose a player to finish their drink.", 10, true, true),
            new WildCardProperties("Task! The player to the left takes a drink.", 10, true, true),
            new WildCardProperties("Task! The player to the right takes a drink.", 10, true, true),
            new WildCardProperties("Task! The oldest player takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! The youngest player takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! The player who last peed takes 3 drinks.", 10, true, true),
            new WildCardProperties("Task! The player with the oldest car takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Whoever last rode on a train takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Anyone who is standing takes 4 drinks, why are you standing? Sit down mate.", 10, true, true),
            new WildCardProperties("Task! Anyone who is sitting takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Whoever has the longest hair takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Whoever is wearing a watch takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Whoever has a necklace on takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Double the ending drink (whoever loses must now do double the consequence).", 10, true, true),
            new WildCardProperties("Task! Have a drink for courage, then deliver a line from your favourite film making it as dramatic as possible!", 10, true, true),
            new WildCardProperties("Task! Give 1 drink for every cheese you can name in 10 seconds.", 10, true, true),
            new WildCardProperties("Task! The shortest person at the table must take 4 drinks then give 4 drinks.", 10, true, true),
            new WildCardProperties("Task! Bare your biceps and flex for everyone. The players next to you each drink 2 for the view.", 10, true, true),
            new WildCardProperties("Task! All females drink 3, and all males drink 3. Equality.", 10, true, true),
            new WildCardProperties("Task! Do a handstand and give out 3 drinks.", 10, true, true),
            new WildCardProperties("Task! Choose someone to drink with their non-dominant hand for the next round.", 10, true, true),
            new WildCardProperties("Task! The next person to laugh must take 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Everyone must not put their elbows on the table for the rest of the game, if you do, take a drink.", 10, true, true),
            new WildCardProperties("Task! Recite the alphabet backward in 10 seconds. Give out drinks for each correct letter before making a mistake or time running out.", 10, true, true),
            new WildCardProperties("Task! You can only drink while making eye contact with someone for the rest of the game.", 10, true, true),
            new WildCardProperties("Task! The person with the longest fingernails takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! The person with the most expensive item on them takes 3 drinks.", 10, true, true),
            new WildCardProperties("Task! The person with the most keys takes 3 drinks.", 10, true, true),
            new WildCardProperties("Task! The person with the longest beard takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Choose someone to take 2 drinks and perform a dance move.", 10, true, true),
            new WildCardProperties("Task! Take a drink for each person with brown eyes in the group.", 10, true, true),
            new WildCardProperties("Task! If you can touch your tongue to the tip of your nose give out 2 drinks, if you can’t take 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Take a drink while doing a split.", 10, true, true),
            new WildCardProperties("Task! Give a toast to the person whos house you are in and take a drink.", 10, true, true),
            new WildCardProperties("Task! The person wearing the most buttons on their shirt takes 3 drinks. Mr Fancy aye.", 10, true, true),
            new WildCardProperties("Task! The person with the most watches takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Give 2 drinks to someone, and serenade that person.", 10, true, true),
            new WildCardProperties("Task! Impersonate your favourite celebrity. Others guess who it is. If they fail, they drink.", 10, true, true),
            new WildCardProperties("Task! Play a round of categories, (your choice of the category) loser takes 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Give out 2 drinks for each double joint you have, take 2 drinks if you don’t have any.", 10, true, true),
            new WildCardProperties("Task! Tell a cheesy joke. If others laugh, you're safe. If not, take 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Draw a picture blindfolded. Others rate your masterpiece. If the crowd does not like it, take 2 drinks.", 10, true, true),
            new WildCardProperties("Task! Name something that should be illegal but aren't. If others agree, you're safe, if not, you take 3 drinks.", 10, true, true),
    };


    public static final WildCardProperties[] TRUTH_WILD_CARDS = {
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on a friend's significant other.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a one-night stand.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever kissed someone of the same gender.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever sent accidentally sent a nude to someone you weren’t meant to.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever used a dating app to stalk someone.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a friends-with-benefits arrangement.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever used online chat room sex calls.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever been offered a sugga daddy/mommy situation.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever skinny-dipped in the ocean or a natural body of water.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a romantic dream about someone in this room.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever made out with a photograph of a celebrity.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever used a dating app while already in a relationship.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a secret admirer.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a steamy hookup in a public place.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on someone in this room.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever kissed someone within minutes of meeting them.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever engaged in role-playing with a partner.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a wardrobe malfunction in public.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a regrettable tattoo.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever drunk called an ex.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on a co-worker.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever lied about your age to someone.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex on a beach.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on a cartoon character.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex, and it ended in a trip to a medical room.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever been offered money for sex. Give out 5 drinks if you have taken the offer.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on a friend's sibling.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever flirted with a teacher or boss.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a romantic encounter during a vacation.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever watched adult content in a public place.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a one-night stand while travelling.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had pretended your sexual partner was a fictional character.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever lied about your relationship status.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex on a rooftop.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on a neighbour.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex on a boat.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever flirted with someone much older or younger than you.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex in a car.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever simped for a social media influencer, and sent them a message.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a steamy chat with a stranger online.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex in a public restroom.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on a friend's ex-partner.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever received a risqué text from the wrong person.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a crush on your boss.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex in the rain.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex/masturbated at work.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex during a festival.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex/masturbated at school.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had a provocative photoshoot.", 10, true, true),
            new WildCardProperties("Truth! Give out a drink if you have ever had sex in an elevator.", 10, true, true),

    };
}
