apply plugin: 'com.android.application'

android {
    compileSdk 37
    defaultConfig {
        applicationId "com.mydomain.countingdowngame"
        minSdkVersion 24
        targetSdkVersion 36
        versionCode 48
        versionName "48"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    ndkVersion "26.1.10909125"

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging = false
        }
    }

    namespace 'com.mydomain.countingdowngame'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildToolsVersion '34.0.0'

    sourceSets {
        main {
            res.srcDirs = [
                    'src/main/res-game',
                    'src/main/res-players',
                    'src/main/res-statistics',
                    'src/main/res-home',
                    'src/main/res-instructions',
                    'src/main/res-settings',
                    'src/main/res'
            ]
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.cardview
    implementation libs.recyclerview
    implementation libs.firebase.crashlytics.buildtools
    implementation libs.material
    implementation libs.core.animation
    testImplementation libs.junit
    testImplementation libs.robolectric
    testImplementation libs.core
    testImplementation libs.ext.junit
    testImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
    implementation libs.dotsindicator
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.espresso.contrib
    implementation libs.adapter.kit
    implementation libs.android.gif.drawable
    implementation libs.glide
    annotationProcessor libs.compiler
    implementation libs.gson
    implementation libs.circleimageview
    implementation libs.ambilwarna
    implementation 'com.daimajia.androidanimations:library:2.4@aar'
    implementation libs.recyclerview.animators
    implementation libs.lottie
    implementation libs.styleabletoast
    implementation libs.socket.io.client

    // Retrofit for API calls
    implementation libs.retrofit
    implementation libs.converter.gson
}
