package com.example.countingdowngame;

import androidx.fragment.app.Fragment;

public class TaskWildCardsFragment extends Fragment {
    Settings_WildCard_Probabilities[] taskWildCards = {
            new Settings_WildCard_Probabilities("Task! Take 1 drink.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Take 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Take 3 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Finish your drink.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Give 1 drink.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Give 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Give 3 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Choose a player to finish their drink.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! The player to the left takes a drink.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! The player to the right takes a drink.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! The oldest player takes 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! The youngest player takes 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! The player who last peed takes 3 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! The player with the oldest car takes 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Whoever last rode on a train takes 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Anyone who is standing takes 4 drinks, why are you standing? Sit down mate.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Anyone who is sitting takes 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Whoever has the longest hair takes 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Whoever is wearing a watch takes 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Whoever has a necklace on takes 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Double the ending drink (whoever loses must now do double the consequence).", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Drink for courage then deliver a line from your favourite film making it as dramatic as possible!", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Give 1 drink for every cheese you can name in 10 seconds.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! The shortest person at the table must take 4 drinks then give 4 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Bare your biceps and flex for everyone. The players next to you each drink 2 for the view.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! All females drink 3, and all males drink 3. Equality.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Do a handstand and give out 3 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Choose someone to drink with their non-dominant hand for the next round.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! The next person to laugh must take 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Everyone must stand on one leg while drinking.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Recite a tongue twister three times without making a mistake, if you do take 3 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Drink your whole drink while making eye contact with someone for the entire duration.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! The person with the longest fingernails takes 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! The person with the most expensive item on them takes 3 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! The person with the most keys takes 3 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! The person with the longest beard takes 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Choose someone to take 2 drinks and perform a breakdance move.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Choose someone to take 2 drinks and recite a poem.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Drink while doing a backbend.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Take a drink while doing a split.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Give a toast to the person who shares your zodiac sign and take a drink.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! The person wearing the most buttons on their shirt takes 3 drinks. Mr Fancy aye.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! The person with the most watches takes 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Perform a dramatic reading of a nursery rhyme. Everyone takes a drink.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Impersonate your favorite celebrity. Others guess who it is. If they fail, they drink.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Everyone imitates a farm animal. The last one to start drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Create a new cocktail recipe using three random ingredients. Others taste and rate it. If it's bad, you drink.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Tell a cheesy joke. If others laugh, you're safe. If not, take 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Draw a picture blindfolded. Others rate your masterpiece. If the crowd does not like it, take 2 drinks.", 10, true, true),
            new Settings_WildCard_Probabilities("Task! Name three things that should be illegal but aren't. If others agree, you're safe, if not, you take 3 drinks.", 10, true, true),
    };

}
