package com.example.countingdowngame;

public class WildCards {
    public static Settings_WildCard_Probabilities[] getDeletableWildCards() {
        return new Settings_WildCard_Probabilities[]{
                new Settings_WildCard_Probabilities("Task! Take 1 drink.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Take 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Take 3 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Finish your drink.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Give 1 drink.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Give 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Give 3 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Choose a player to finish their drink.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! The player to the left takes a drink.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! The player to the right takes a drink.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! The oldest player takes 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! The youngest player takes 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! The player who last peed takes 3 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! The player with the oldest car takes 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Whoever last rode on a train takes 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Anyone who is standing takes 4 drinks, why are you standing? Sit down mate.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Anyone who is sitting takes 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Whoever has the longest hair takes 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Whoever is wearing a watch takes 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Whoever has a necklace on takes 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Double the ending drink (whoever loses must now do double the consequence).", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Drink for courage then deliver a line from your favourite film making it as dramatic as possible!", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Give 1 drink for every cheese you can name in 10 seconds.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! The shortest person at the table must take 4 drinks then give 4 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Bare your biceps and flex for everyone. The players next to you each drink 2 for the view.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! All females drink 3, and all males drink 3. Equality.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Do a handstand and give out 3 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Choose someone to drink with their non-dominant hand for the next round.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! The next person to laugh must take 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Everyone must stand on one leg while drinking.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Recite a tongue twister three times without making a mistake, if you do take 3 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Drink your whole drink while making eye contact with someone for the entire duration.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! The person with the longest fingernails takes 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! The person with the most expensive item on them takes 3 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! The person with the most keys takes 3 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! The person with the longest beard takes 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Choose someone to take 2 drinks and perform a breakdance move.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Choose someone to take 2 drinks and recite a poem.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Drink while doing a backbend.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Take a drink while doing a split.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Give a toast to the person who shares your zodiac sign and take a drink.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! The person wearing the most buttons on their shirt takes 3 drinks. Mr Fancy aye.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! The person with the most watches takes 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Perform a dramatic reading of a nursery rhyme. Everyone takes a drink.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Impersonate your favorite celebrity. Others guess who it is. If they fail, they drink.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Everyone imitates a farm animal. The last one to start drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Create a new cocktail recipe using three random ingredients. Others taste and rate it. If it's bad, you drink.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Tell a cheesy joke. If others laugh, you're safe. If not, take 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Draw a picture blindfolded. Others rate your masterpiece. If the crowd does not like it, take 2 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Task! Name three things that should be illegal but aren't. If others agree, you're safe, if not, you take 3 drinks.", 10, true, true),

                new Settings_WildCard_Probabilities("Truth! Have you ever had a crush on a friend's significant other?", 10, true, true),
                new Settings_WildCard_Probabilities("Truth! What is your most regrettable romantic rejection?", 10, true, true),
                new Settings_WildCard_Probabilities("Truth! Have you ever stolen something? If yes, what and why?", 10, true, true),
                new Settings_WildCard_Probabilities("Truth! What is your most crazy sex story?", 10, true, true),
                new Settings_WildCard_Probabilities("Truth! Have you ever engaged in a naughty video chat or phone sex?", 10, true, true),
                new Settings_WildCard_Probabilities("Truth! Have you ever watched adult content while in a public setting?", 10, true, true),
                new Settings_WildCard_Probabilities("Truth! Have you ever had a sensual massage with a happy ending?", 10, true, true),
                new Settings_WildCard_Probabilities("Truth! Have you ever betrayed a friend's trust and never apologized?", 10, true, true),
                new Settings_WildCard_Probabilities("Truth! Have you ever knowingly ruined someone's relationship?", 10, true, true),
                new Settings_WildCard_Probabilities("Truth! Have you ever stolen something valuable from a family member?", 10, true, true),
                new Settings_WildCard_Probabilities("Truth! Have you ever caused someone to lose their job?", 10, true, true),
                new Settings_WildCard_Probabilities("Truth! Have you ever destroyed evidence to cover up your wrongdoing?", 10, true, true),

                new Settings_WildCard_Probabilities("Quiz! Name two famous people with the same initials as yours. If you can't, take 2 drinks, if you can everyone takes 3 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Name five countries starting with the letter A. If you can't, take 3 drinks.", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Can you recite the first 7 digits of pi? If yes, go ahead.", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! In which year was the Great Fire of London?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Can you name all four fundamental forces in physics?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who wrote the famous novel 'To Kill a Mockingbird'?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! How many bones are there in the human body?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who painted the famous artwork 'The Starry Night'?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! What is the scientific name for the common cold?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! In which country is the ancient city of Machu Picchu located?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who developed the theory of general relativity?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! What is the chemical formula for glucose?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! How many symphonies did Ludwig van Beethoven compose?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who is credited with inventing the World Wide Web?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! What is the largest planet in our solar system?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Can you name all seven colors of the rainbow in order?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! What is the largest organ in the human body?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who painted the famous artwork 'The Last Supper'?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! How many countries are members of the United Nations?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! What is the capital of Australia?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Can you name the longest river in the world?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! What is the formula for calculating the area of a circle?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who wrote the famous novel '1984'?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! How many strings does a standard violin have?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! What is the chemical symbol for silver on the periodic table?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who directed the movie 'Pulp Fiction'?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! How many chromosomes are in a human body cell?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who is the Greek god of the sea?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! What is the national animal of Canada?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! How many time zones are there in the world?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who wrote the famous novel 'Moby-Dick'?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! What is the largest species of shark?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who composed the famous classical symphony 'Symphony No. 10'?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! How many players are there on a basketball team?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! What is the chemical symbol for iron on the periodic table?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who directed the movie 'The Shawshank Redemption'?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! How many colors are there in a rainbow?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who is the author of the novel 'The Catcher in the Rye'?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! What is the boiling point of water in Fahrenheit?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! What is the deepest ocean on Earth?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who is the author of the novel 'The Great Gatsby'?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! How many legs does a spider have?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! What is the chemical symbol for helium on the periodic table?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who directed the movie 'The Godfather'?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! How many sides does a heptagon have?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who is the current Prime Minister of Japan?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! What is the largest continent in the world?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! Who is the author of the novel 'The Lord of the Rings'?", 10, true, true),
                new Settings_WildCard_Probabilities("Quiz! How many players are there on a soccer team?", 10, true, true),
        };
    }


    public static Settings_WildCard_Probabilities[] getNonDeletableWildcards() {
        return new Settings_WildCard_Probabilities[]{
                new Settings_WildCard_Probabilities("Double the current number and go again!", 80, true, false),
                new Settings_WildCard_Probabilities("Half the current number and go again!", 80, true, false),
                new Settings_WildCard_Probabilities("Reset the number!", 80, true, false),
                new Settings_WildCard_Probabilities("Reverse the turn order!", 80, true, false),
        };
    }
}
